#!/usr/bin/env Rscript
# 14_5_uq_normalization_sensitivity.R (Agent B4 — 2026-05-20)
# ---------------------------------------------------------------------------
# TMM vs UQ (upper-quartile) normalization sensitivity for §1.B.
#
# RATIONALE
#   TMM (Robinson & Oshlack 2010) assumes the majority of genes are NOT
#   differentially expressed. In MASLD livers this assumption can be violated
#   (broad metabolic remodeling). UQ is less sensitive to global shifts.
#
# DESIGN
#   - Re-run dream Disease vs Control mega-analysis with UQ normalization
#     (edgeR::calcNormFactors(method = "upperquartile")) keeping all other
#     pipeline choices identical (5-cohort yaml include_in_mega, voom, dream
#     ~ group_binary + inferred_sex + (1|dataset)).
#   - Compare DEG sets at padj < 0.05, |logFC| > 0.5 vs canonical TMM dream.
#   - Report Jaccard, directional concordance, top-N preservation.
#
# OUTPUT
#   RNA-seq/results/audit_sensitivity/tmm_vs_uq/dream_results_uq.csv
#   RNA-seq/results/audit_sensitivity/tmm_vs_uq/jaccard_summary.csv
#   (REPORT.md generated by tmm_directional_bias_audit.R post-hoc, sharing dir)
# ---------------------------------------------------------------------------

set.seed(42)
Sys.setenv(R_PARALLEL_SEED = "42")

suppressPackageStartupMessages({
  library(reformulas)
  library(lme4)
  library(data.table)
  library(edgeR)
  library(yaml)
})
# Inject reformulas into lme4 (same hack as 05_dream_mega_analysis.R)
ns_lme4 <- asNamespace("lme4")
for (fn in c("findbars", "nobars", "subbars", "rebuildFormula")) {
  if (exists(fn, envir = ns_lme4)) {
    try({
      unlockBinding(fn, ns_lme4)
      assign(fn, get(fn, asNamespace("reformulas")), envir = ns_lme4)
      lockBinding(fn, ns_lme4)
    }, silent = TRUE)
  }
}
suppressPackageStartupMessages({
  library(variancePartition)
  library(BiocParallel)
})

PROJ <- Sys.getenv("MASLD_PROJECT_ROOT",
                   "/gpfs/commons/groups/sanjana_lab/Cas13/MASLD_library_design")
INT  <- file.path(PROJ, "RNA-seq/Human/Patient_Cohorts/analysis/integration")
RDIR <- file.path(INT, "results/integration")
OUT_DIR <- file.path(PROJ, "RNA-seq/results/audit_sensitivity/tmm_vs_uq")
dir.create(OUT_DIR, showWarnings = FALSE, recursive = TRUE)

ncpus <- as.integer(Sys.getenv("SLURM_CPUS_PER_TASK", "8"))
param <- if (ncpus > 1) MulticoreParam(ncpus) else SerialParam()

cat("Loading merged_dge.rds (uses canonical TMM norm factors)...\n")
dge <- readRDS(file.path(RDIR, "merged_dge.rds"))

# yaml-aware 5-cohort filter
ycfg <- yaml::read_yaml(file.path(PROJ, "config/human_datasets.yaml"))$datasets
mega_cohorts <- names(Filter(function(d) isTRUE(d$de$include_in_mega), ycfg))
dge_mega <- dge[, dge$samples$dataset %in% mega_cohorts]
cat("Samples:", ncol(dge_mega), "\n")

# --- SWAP normalization: TMM -> UQ ---
cat("Recomputing norm factors with method = 'upperquartile'...\n")
dge_mega$samples$norm.factors <- 1.0  # reset
dge_mega <- calcNormFactors(dge_mega, method = "upperquartile")
cat("UQ norm factor summary:\n"); print(summary(dge_mega$samples$norm.factors))

meta_new <- readRDS(file.path(RDIR, "meta_matched.rds"))
matched_sex <- meta_new$inferred_sex[match(colnames(dge_mega), meta_new$sample_id)]
info <- data.frame(
  group_binary = factor(dge_mega$samples$group_binary, levels = c("Control", "Disease")),
  dataset      = factor(dge_mega$samples$dataset),
  inferred_sex = factor(matched_sex),
  stringsAsFactors = FALSE
)
rownames(info) <- colnames(dge_mega)

form <- ~ group_binary + inferred_sex + (1|dataset)
cat("Formula:", deparse(form), "\n")
cat("Running voomWithDreamWeights (UQ)...\n")
v <- suppressWarnings(voomWithDreamWeights(dge_mega, form, info, BPPARAM = param))
cat("Running dream (UQ)...\n")
fit <- suppressWarnings(dream(v, form, info, BPPARAM = param))
res <- topTable(fit, coef = "group_binaryDisease", number = Inf, sort.by = "none")
res$gene <- rownames(res)
res_dt <- as.data.table(res)
setnames(res_dt, "adj.P.Val", "padj")

fwrite(res_dt, file.path(OUT_DIR, "dream_results_uq.csv"))
cat("Wrote dream_results_uq.csv (", nrow(res_dt), "genes)\n")

# --- Compare vs canonical TMM dream ---
tmm <- fread(file.path(RDIR, "dream_results.csv"))
setnames(tmm, c("logFC", "padj"), c("logFC_tmm", "padj_tmm"), skip_absent = TRUE)
m <- merge(tmm[, .(gene, logFC_tmm, padj_tmm)],
           res_dt[, .(gene, logFC_uq = logFC, padj_uq = padj)], by = "gene")

jaccard <- function(a, b) length(intersect(a, b)) / length(union(a, b))

# Tier 1 DEG (padj<0.05, |LFC|>0.5)
tmm_deg <- m[padj_tmm < 0.05 & abs(logFC_tmm) > 0.5, gene]
uq_deg  <- m[padj_uq  < 0.05 & abs(logFC_uq)  > 0.5, gene]
# Looser (padj<0.05, |LFC|>0.3)
tmm_deg_03 <- m[padj_tmm < 0.05 & abs(logFC_tmm) > 0.3, gene]
uq_deg_03  <- m[padj_uq  < 0.05 & abs(logFC_uq)  > 0.3, gene]

shared_genes_both <- intersect(tmm_deg, uq_deg)
dir_concord <- if (length(shared_genes_both) > 0) {
  mean(sign(m[gene %in% shared_genes_both, logFC_tmm]) ==
       sign(m[gene %in% shared_genes_both, logFC_uq]))
} else NA_real_

# Overall LFC correlation
lfc_rho <- cor(m$logFC_tmm, m$logFC_uq, method = "spearman", use = "complete.obs")
lfc_pear <- cor(m$logFC_tmm, m$logFC_uq, method = "pearson", use = "complete.obs")

summary_dt <- data.table(
  metric = c("n_tmm_deg_lfc05", "n_uq_deg_lfc05", "jaccard_lfc05",
             "n_tmm_deg_lfc03", "n_uq_deg_lfc03", "jaccard_lfc03",
             "n_shared_lfc05_directional_concordance",
             "spearman_lfc_all_genes", "pearson_lfc_all_genes"),
  value  = c(length(tmm_deg), length(uq_deg), jaccard(tmm_deg, uq_deg),
             length(tmm_deg_03), length(uq_deg_03), jaccard(tmm_deg_03, uq_deg_03),
             dir_concord, lfc_rho, lfc_pear)
)
fwrite(summary_dt, file.path(OUT_DIR, "jaccard_summary.csv"))
cat("\n=== TMM vs UQ summary ===\n"); print(summary_dt)
cat("\nWrote jaccard_summary.csv\n")
cat("Done.\n")
