#!/usr/bin/env Rscript
# 36b_sceqtl_coloc_ukbb.R
# ---------------------------------------------------------------------------
# UKBB ALT GWAS COLOC with sc-eQTL (Multi-Cell-Type, All eGenes)
#
# Uses UKBB ALT GWAS (GCST90019492, quantitative, N=343,850) instead of
# Ghodsian case-control GWAS. Tests ALL eGenes (no DEG filter, no GWAS gate)
# since UKBB ALT is a quantitative trait with different signal architecture.
#
# Key differences from Script 36:
#   - GWAS: UKBB ALT (quantitative) vs Ghodsian (case-control)
#   - No GWAS p-value gate (let PP.H4 handle specificity)
#   - No DEG filter (test all eGenes, not just dream DEGs)
#   - No MR (already done in Script 36)
#   - GWAS type = "quant" (not "cc")
#
# Expected: recovers ~10 Zenodo-validated NAFLD genes that colocalize
#           with UKBB ALT but NOT with Ghodsian GWAS.
# ---------------------------------------------------------------------------

suppressPackageStartupMessages({
  library(coloc)
  library(data.table)
})

cat("=== Script 36b: sc-eQTL COLOC with UKBB ALT GWAS ===\n")
cat("Start time:", format(Sys.time()), "\n\n")

# ==============================================================================
# Configuration
# ==============================================================================
BASE_DIR    <- "/gpfs/commons/groups/sanjana_lab/Cas13/MASLD_library_design"
GWAS_FILE   <- file.path(BASE_DIR, "GWAS/MR_Data/GCST90019492_UKBB_ALT_harmonised.tsv.gz")
EQTL_DIR    <- file.path(BASE_DIR, "RNA-seq/References/eQTL/MASLD_sc_eQTL_2025")
RESULTS_DIR <- file.path(BASE_DIR, "RNA-seq/results/causal_inference/sceqtl")

dir.create(RESULTS_DIR, recursive = TRUE, showWarnings = FALSE)

# Cell types to analyze
CELL_TYPES <- c("hepatocyte", "endothelial_cell", "cholangiocyte", "stellate_cell")

# Formatted eQTL file paths (generated by Script 36 if not already present)
eqtl_files <- setNames(
  file.path(EQTL_DIR, paste0(CELL_TYPES, "_twas_formatted.txt.gz")),
  CELL_TYPES
)

# Raw eQTL file paths (for formatting if needed)
raw_eqtl_files <- setNames(
  file.path(EQTL_DIR, "Zenodo/sceQTL_output/liver_eQTLs",
            paste0("liver_eQTLs_summary_stats_", CELL_TYPES, ".txt.gz")),
  CELL_TYPES
)

# Parameters — UKBB ALT is quantitative
GWAS_TYPE <- "quant"
GWAS_N    <- 343850L    # UKBB ALT sample size
EQTL_N    <- 312L       # Number of donors in sc-eQTL pseudobulk
CIS_WINDOW <- 1e6       # +/- 1Mb cis-window for COLOC

# COLOC priors (matching original sc-eQTL paper)
COLOC_P1  <- 1e-4
COLOC_P2  <- 1e-4
COLOC_P12 <- 5e-6

# ==============================================================================
# Helper: Format eQTL file (reused from Script 36)
# ==============================================================================
format_eqtl_file <- function(input_file, output_file) {
  cat("  Formatting", basename(input_file), "->", basename(output_file), "...\n")
  dt <- fread(input_file)
  cat("    Raw rows:", nrow(dt), "\n")

  snp_parts <- tstrsplit(dt$snp_chr_pos_ref_alt, "_", keep = 1:4)

  out <- data.table(
    gene_id    = dt$gene,
    variant_id = paste0("chr", snp_parts[[1]], "_", snp_parts[[2]], "_",
                        snp_parts[[3]], "_", snp_parts[[4]], "_b38"),
    chromosome = paste0("chr", snp_parts[[1]]),
    position   = snp_parts[[2]],
    ref        = snp_parts[[3]],
    alt        = snp_parts[[4]],
    beta_all   = dt$Beta_all_cells,
    se_all     = dt$Std_Error_all_cells,
    pval_all   = dt$pval_all_cells,
    beta_masld = dt$Beta_MASLD_cells,
    se_masld   = dt$Std_Error_MASLD_cells,
    pval_masld = dt$pval_MASLD_cells,
    beta_ctrl  = dt$Beta_control_cells,
    se_ctrl    = dt$Std_Error_control_cells,
    pval_ctrl  = dt$pval_control_cells
  )

  out <- out[!is.na(pval_all) & !is.na(position)]
  cat("    Formatted rows:", nrow(out), "\n")

  fwrite(out, output_file, sep = "\t", compress = "gzip")
  return(invisible(TRUE))
}

# ==============================================================================
# Helper: Allele harmonization for COLOC
# ==============================================================================
harmonize_alleles_coloc <- function(dt) {
  dt <- copy(dt)
  comp <- c("A" = "T", "T" = "A", "C" = "G", "G" = "C")

  dt[, match_type := "none"]
  dt[ref == other_allele & alt == effect_allele, match_type := "direct"]
  dt[ref == effect_allele & alt == other_allele, match_type := "flipped"]

  # Remove strand-ambiguous variants that failed direct/flipped match
  # (complement matching unreliable for A/T and C/G pairs)
  dt[, is_ambiguous := (ref %in% c("A","T") & alt %in% c("A","T")) |
                        (ref %in% c("C","G") & alt %in% c("C","G"))]
  n_ambig_unmatched <- sum(dt$is_ambiguous & dt$match_type == "none", na.rm = TRUE)
  cat("    Strand-ambiguous unmatched:", n_ambig_unmatched, "\n")
  dt <- dt[!(is_ambiguous & match_type == "none")]

  # Complement match for remaining non-ambiguous strand SNPs
  dt[match_type == "none" & nchar(ref) == 1 & nchar(alt) == 1,
     match_type := fifelse(
       comp[ref] == other_allele & comp[alt] == effect_allele, "direct",
       fifelse(comp[ref] == effect_allele & comp[alt] == other_allele, "flipped",
               "none")
     )]

  n_direct  <- sum(dt$match_type == "direct")
  n_flipped <- sum(dt$match_type == "flipped")
  n_none    <- sum(dt$match_type == "none")
  cat("    Allele harmonization: direct=", n_direct, " flipped=", n_flipped,
      " dropped=", n_none, "\n")

  dt <- dt[match_type != "none"]

  if (any(dt$match_type == "flipped")) {
    flip_idx <- dt$match_type == "flipped"
    dt[flip_idx, beta_all := -beta_all]
    dt[flip_idx, beta_masld := -beta_masld]
    dt[flip_idx, beta_ctrl := -beta_ctrl]
  }

  dt[, is_ambiguous := NULL]
  return(dt)
}

# ==============================================================================
# Helper: Run COLOC for a given cell type's eQTL data (no GWAS gate)
# ==============================================================================
run_coloc_for_celltype <- function(merged_dt, cell_type) {
  cat("\n  --- COLOC (", cell_type, ") ---\n")

  candidates <- unique(merged_dt$gene_id)
  cat("    Candidate eGenes:", length(candidates), "\n")

  results_list <- list()
  n_tested <- 0L
  n_skipped_few_snps <- 0L

  conditions <- list(
    all   = list(beta_col = "beta_all",   se_col = "se_all",   pval_col = "pval_all"),
    masld = list(beta_col = "beta_masld", se_col = "se_masld", pval_col = "pval_masld"),
    ctrl  = list(beta_col = "beta_ctrl",  se_col = "se_ctrl",  pval_col = "pval_ctrl")
  )

  for (g in candidates) {
    gene_data <- merged_dt[gene_id == g]
    median_pos <- median(gene_data$pos, na.rm = TRUE)
    gene_data <- gene_data[abs(pos - median_pos) <= CIS_WINDOW]

    if (nrow(gene_data) < 10) {
      n_skipped_few_snps <- n_skipped_few_snps + 1L
      next
    }

    # NO GWAS gate — test every gene, let PP.H4 handle specificity

    n_tested <- n_tested + 1L
    row <- data.table(gene = g, cell_type = cell_type, n_snps = nrow(gene_data))

    for (cond_name in names(conditions)) {
      cond <- conditions[[cond_name]]
      beta_vals <- gene_data[[cond$beta_col]]
      se_vals   <- gene_data[[cond$se_col]]

      valid <- !is.na(beta_vals) & !is.na(se_vals) & se_vals > 0
      if (sum(valid) < 10) {
        row[[paste0("PP.H4_", cond_name)]] <- NA_real_
        row[[paste0("PP.H3_", cond_name)]] <- NA_real_
        row[[paste0("n_snps_", cond_name)]] <- sum(valid)
        next
      }

      eqtl_dataset <- list(
        snp     = gene_data$merge_key[valid],
        beta    = beta_vals[valid],
        varbeta = (se_vals[valid])^2,
        type    = "quant",
        sdY     = 1,
        N       = EQTL_N
      )

      gwas_sub <- list(
        snp     = gene_data$merge_key[valid],
        beta    = gene_data$beta_gwas[valid],
        varbeta = (gene_data$standard_error[valid])^2,
        type    = GWAS_TYPE,
        sdY     = 1,
        N       = GWAS_N
      )

      res <- tryCatch(
        coloc.abf(dataset1 = gwas_sub, dataset2 = eqtl_dataset,
                  p1 = COLOC_P1, p2 = COLOC_P2, p12 = COLOC_P12),
        error = function(e) { NULL }
      )

      if (!is.null(res)) {
        row[[paste0("PP.H0_", cond_name)]] <- res$summary["PP.H0.abf"]
        row[[paste0("PP.H1_", cond_name)]] <- res$summary["PP.H1.abf"]
        row[[paste0("PP.H2_", cond_name)]] <- res$summary["PP.H2.abf"]
        row[[paste0("PP.H3_", cond_name)]] <- res$summary["PP.H3.abf"]
        row[[paste0("PP.H4_", cond_name)]] <- res$summary["PP.H4.abf"]
        row[[paste0("n_snps_", cond_name)]] <- sum(valid)

        top_snp <- res$results[which.max(res$results$SNP.PP.H4), ]
        row[[paste0("top_snp_", cond_name)]] <- top_snp$snp
        row[[paste0("top_snp_PP_", cond_name)]] <- top_snp$SNP.PP.H4
      } else {
        row[[paste0("PP.H4_", cond_name)]] <- NA_real_
        row[[paste0("PP.H3_", cond_name)]] <- NA_real_
        row[[paste0("n_snps_", cond_name)]] <- sum(valid)
      }
    }

    results_list[[g]] <- row

    # Progress: log every 500 genes
    if (n_tested %% 500 == 0) {
      cat("    Processed", n_tested, "genes...\n")
    }
  }

  cat("    Genes tested:", n_tested, "\n")
  cat("    Skipped (<10 SNPs):", n_skipped_few_snps, "\n")

  if (length(results_list) > 0) {
    return(rbindlist(results_list, fill = TRUE))
  }
  return(NULL)
}

# ==============================================================================
# 1. Load UKBB ALT GWAS
# ==============================================================================
cat("--- Step 1: Loading UKBB ALT GWAS (GCST90019492) ---\n")
gwas <- fread(GWAS_FILE)
cat("  Raw GWAS rows:", nrow(gwas), "\n")

# Filter to valid rows
gwas <- gwas[!is.na(chromosome) & !is.na(base_pair_location) & !is.na(p_value)]
gwas[, chr := as.integer(chromosome)]
gwas[, pos_hg38 := as.integer(base_pair_location)]
gwas <- gwas[!is.na(chr) & chr %in% 1:22]  # Autosomal only

# Deduplicate by position (keep lowest p-value)
gwas <- gwas[order(chr, pos_hg38, p_value)]
gwas <- gwas[!duplicated(paste(chr, pos_hg38))]
gwas[, merge_key := paste0(chr, ":", pos_hg38)]

cat("  GWAS after dedup:", nrow(gwas), "variants\n")
cat("  Genome-wide significant (p<5e-8):", sum(gwas$p_value < 5e-8), "\n")

# ==============================================================================
# 2. Format eQTL files if needed
# ==============================================================================
cat("\n--- Step 2: Checking/formatting eQTL files ---\n")
for (ct in CELL_TYPES) {
  if (!file.exists(eqtl_files[ct])) {
    if (file.exists(raw_eqtl_files[ct])) {
      format_eqtl_file(raw_eqtl_files[ct], eqtl_files[ct])
    } else {
      cat("  WARNING: Raw eQTL file not found for", ct, "\n")
    }
  } else {
    cat("  ", ct, "formatted file exists\n")
  }
}

# ==============================================================================
# 3. Process each cell type
# ==============================================================================
all_coloc_results <- list()

for (ct in CELL_TYPES) {
  cat("\n", strrep("=", 60), "\n")
  cat("Processing cell type:", ct, "\n")
  cat(strrep("=", 60), "\n")

  if (!file.exists(eqtl_files[ct])) {
    cat("  Skipping — formatted eQTL file not found\n")
    next
  }

  # Load eQTL data (ALL eGenes, no DEG filter)
  eqtl <- fread(eqtl_files[ct])
  cat("  Loaded sc-eQTL rows:", nrow(eqtl), "\n")

  eqtl[, chr := as.integer(sub("chr", "", chromosome))]
  eqtl[, pos := as.integer(position)]
  eqtl[, merge_key := paste0(chr, ":", pos)]

  # Count unique eGenes
  cat("  Unique eGenes:", uniqueN(eqtl$gene_id), "\n")

  # Merge with GWAS by position
  merged_gwas_eqtl <- merge(eqtl, gwas, by = "merge_key", suffixes = c("", ".gwas"))
  cat("  Overlap SNPs (eQTL x GWAS):", nrow(merged_gwas_eqtl), "\n")

  if (nrow(merged_gwas_eqtl) < 10) {
    cat("  Too few overlapping SNPs for", ct, "\n")
    next
  }

  # Rename GWAS beta to avoid conflict with eQTL beta columns
  setnames(merged_gwas_eqtl, "beta", "beta_gwas", skip_absent = TRUE)

  # Harmonize alleles
  merged_gwas_eqtl <- harmonize_alleles_coloc(merged_gwas_eqtl)
  cat("  After allele harmonization:", nrow(merged_gwas_eqtl), "\n")
  cat("  Unique eGenes with overlap:", uniqueN(merged_gwas_eqtl$gene_id), "\n")

  if (nrow(merged_gwas_eqtl) < 10) {
    cat("  Too few harmonized SNPs for", ct, "\n")
    next
  }

  coloc_res <- run_coloc_for_celltype(merged_gwas_eqtl, ct)
  if (!is.null(coloc_res)) {
    all_coloc_results[[ct]] <- coloc_res
    fwrite(coloc_res, file.path(RESULTS_DIR,
           paste0("coloc_results_ukbb_alt_", ct, ".csv")))
    cat("  Saved: coloc_results_ukbb_alt_", ct, ".csv\n")
  }
}

# ==============================================================================
# 4. Compile unified results
# ==============================================================================
cat("\n", strrep("=", 60), "\n")
cat("=== Compiling UKBB ALT COLOC Results ===\n")
cat(strrep("=", 60), "\n")

if (length(all_coloc_results) > 0) {
  coloc_combined <- rbindlist(all_coloc_results, fill = TRUE)
  setorder(coloc_combined, -PP.H4_all)
  fwrite(coloc_combined, file.path(RESULTS_DIR, "coloc_results_ukbb_alt.csv"))

  # Summary per cell type
  cat("\n  COLOC Summary (no GWAS gate):\n")
  for (ct in names(all_coloc_results)) {
    ct_res <- all_coloc_results[[ct]]
    cat("\n    ---", ct, "---\n")
    cat("      Genes tested:", nrow(ct_res), "\n")
    cat("      PP.H4_all > 0.8:", sum(ct_res$PP.H4_all > 0.8, na.rm = TRUE), "\n")
    cat("      PP.H4_all > 0.5:", sum(ct_res$PP.H4_all > 0.5, na.rm = TRUE), "\n")
    cat("      PP.H4_all > 0.3:", sum(ct_res$PP.H4_all > 0.3, na.rm = TRUE), "\n")
    cat("      PP.H4_masld > 0.5:", sum(ct_res$PP.H4_masld > 0.5, na.rm = TRUE), "\n")
  }

  # Top 20 hits
  cat("\n  Top 20 COLOC hits across all cell types:\n")
  top20 <- head(coloc_combined[!is.na(PP.H4_all)][order(-PP.H4_all)], 20)
  for (i in seq_len(nrow(top20))) {
    cat("    ", top20$gene[i], " (", top20$cell_type[i], "): PP.H4_all=",
        round(top20$PP.H4_all[i], 3),
        " PP.H4_masld=", round(top20$PP.H4_masld[i], 3),
        " (n=", top20$n_snps[i], ")\n")
  }

  # Multi-cell-type summary
  gene_best <- coloc_combined[, .(
    best_PP.H4_all   = max(PP.H4_all, na.rm = TRUE),
    best_PP.H4_masld = max(PP.H4_masld, na.rm = TRUE),
    best_cell_type   = cell_type[which.max(PP.H4_all)],
    n_cell_types     = uniqueN(cell_type),
    cell_types_tested = paste(unique(cell_type), collapse = ";")
  ), by = gene]
  setorder(gene_best, -best_PP.H4_all)
  fwrite(gene_best, file.path(RESULTS_DIR, "sceqtl_coloc_ukbb_alt_summary.csv"))

  cat("\n  Multi-cell-type summary:\n")
  cat("    Unique genes tested:", nrow(gene_best), "\n")
  cat("    Genes with PP.H4 > 0.8 (any cell type):",
      sum(gene_best$best_PP.H4_all > 0.8, na.rm = TRUE), "\n")
  cat("    Genes with PP.H4 > 0.5 (any cell type):",
      sum(gene_best$best_PP.H4_all > 0.5, na.rm = TRUE), "\n")
  cat("    Genes with PP.H4 > 0.3 (any cell type):",
      sum(gene_best$best_PP.H4_all > 0.3, na.rm = TRUE), "\n")

  # Zenodo validation check
  zenodo_genes <- c("HSD17B13", "EFHD1", "CHEK2", "MAP1LC3A", "SPTLC3",
                     "APOH", "MFHAS1", "ETS2", "LCOR", "USP40", "ALAD")
  cat("\n  Zenodo NAFLD gene validation:\n")
  for (g in zenodo_genes) {
    hit <- gene_best[gene == g]
    if (nrow(hit) > 0) {
      cat("    ", g, ": PP.H4=", round(hit$best_PP.H4_all[1], 3),
          " (", hit$best_cell_type[1], ")\n")
    } else {
      cat("    ", g, ": not tested (no eQTL overlap)\n")
    }
  }
} else {
  cat("  No COLOC results across any cell type.\n")
}

cat("\n=== Script 36b: Complete ===\n")
cat("End time:", format(Sys.time()), "\n")
