#!/usr/bin/env python3
"""
02_snapatac2_processing.py
==========================
Module 2, Step 2: SnapATAC2 scATAC-seq processing for GSE244832 human liver.

GSE244832 uses combinatorial indexing (NOT 10x Chromium). Fragment files are
generated by the custom bowtie2 alignment pipeline (01_align_scatac.sh).

Pipeline:
  1. Import fragments per donor (backed h5ad) + QC + tile matrix + doublet removal
  2. Create AnnDataSet -> feature selection -> spectral embedding (LSI)
  3. Harmony batch correction (external harmonypy)
  4. UMAP + Leiden clustering
  5. Cell type annotation via gene activity scores (canonical liver markers)
  6. Peak calling (MACS3 via AnnDataSet fragment access)
  7. Differential accessibility per cell type (MASLD vs Normal)

API Notes (SnapATAC2 v2.8):
  - import_fragments(file=) creates backed AnnData preserving fragment references
  - filter_cells() for in-place QC on backed AnnData
  - add_tile_matrix() populates .X; must be called before scrublet
  - filter_doublets() for in-place doublet removal
  - AnnDataSet preserves fragment refs for make_gene_matrix and macs3
  - diff_test takes list[str] cell names, NOT boolean masks
  - diff_test returns polars DataFrame
"""

import snapatac2 as snap
import numpy as np
import pandas as pd
import os
import sys
import argparse
import logging
import json
import gc
from datetime import datetime
from pathlib import Path

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    HAS_MPL = True
except ImportError:
    HAS_MPL = False


# =============================================================================
# Logging
# =============================================================================

def setup_logging(output_dir: str) -> logging.Logger:
    log_dir = os.path.join(output_dir, "logs")
    os.makedirs(log_dir, exist_ok=True)
    log_file = os.path.join(
        log_dir, f"snapatac2_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
    )
    logger = logging.getLogger("snapatac2")
    logger.setLevel(logging.INFO)
    fmt = logging.Formatter(
        "[%(asctime)s] %(levelname)s - %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
    )
    fh = logging.FileHandler(log_file)
    fh.setFormatter(fmt)
    logger.addHandler(fh)
    sh = logging.StreamHandler(sys.stdout)
    sh.setFormatter(fmt)
    logger.addHandler(sh)
    return logger


# =============================================================================
# Arguments
# =============================================================================

def parse_args():
    parser = argparse.ArgumentParser(
        description="SnapATAC2 scATAC-seq processing for GSE244832"
    )
    parser.add_argument("--input_dir", required=True,
                        help="Directory with {donor_id}_fragments.tsv.gz files")
    parser.add_argument("--output_dir", required=True,
                        help="Results directory")
    parser.add_argument("--sample_csv", required=True,
                        help="Sample CSV with donor_id, condition columns")
    parser.add_argument("--n_workers", type=int, default=4)
    parser.add_argument("--min_tsse", type=float, default=4.0)
    parser.add_argument("--min_frags", type=int, default=1000)
    parser.add_argument("--max_frags", type=int, default=100000)
    parser.add_argument("--tile_size", type=int, default=500)
    parser.add_argument("--n_features", type=int, default=50000)
    parser.add_argument("--leiden_resolution", type=float, default=1.0)
    parser.add_argument("--skip_da", action="store_true")
    return parser.parse_args()


# =============================================================================
# Helpers
# =============================================================================

def load_sample_metadata(csv_path: str) -> pd.DataFrame:
    lines = [line for line in open(csv_path) if not line.startswith("#")]
    from io import StringIO
    return pd.read_csv(StringIO("".join(lines)))


def discover_donors(input_dir: str, sample_df: pd.DataFrame, logger):
    """Find fragment files for each donor."""
    donors = []
    for _, row in sample_df.iterrows():
        donor_id = row["donor_id"]
        condition = row.get("condition", "Unknown")
        frag_file = os.path.join(input_dir, f"{donor_id}_fragments.tsv.gz")
        if not os.path.isfile(frag_file):
            frag_file = os.path.join(input_dir, donor_id, "outs", "atac_fragments.tsv.gz")
        if os.path.isfile(frag_file):
            donors.append((donor_id, condition, frag_file))
        else:
            logger.warning("Fragment file missing for %s - skipping", donor_id)
    return donors


def plot_qc(adata, output_dir: str, logger):
    if not HAS_MPL:
        return
    qc_dir = os.path.join(output_dir, "qc")
    os.makedirs(qc_dir, exist_ok=True)

    if "tsse" in adata.obs.columns:
        fig, ax = plt.subplots(figsize=(8, 5))
        ax.hist(adata.obs["tsse"].values, bins=100, edgecolor="black", alpha=0.7)
        ax.axvline(4.0, color="red", linestyle="--", label="TSS >= 4")
        ax.set_xlabel("TSS Enrichment Score")
        ax.set_ylabel("Cells")
        ax.set_title("TSS Enrichment Distribution (post-QC)")
        ax.legend()
        fig.savefig(os.path.join(qc_dir, "tsse_histogram.png"), dpi=150, bbox_inches="tight")
        plt.close(fig)

    if "n_fragment" in adata.obs.columns:
        fig, ax = plt.subplots(figsize=(8, 5))
        ax.hist(np.log10(adata.obs["n_fragment"].values + 1), bins=100, edgecolor="black", alpha=0.7)
        ax.set_xlabel("log10(n_fragments + 1)")
        ax.set_ylabel("Cells")
        ax.set_title("Fragment Count Distribution (post-QC)")
        fig.savefig(os.path.join(qc_dir, "fragment_count_histogram.png"), dpi=150, bbox_inches="tight")
        plt.close(fig)

    if "X_umap" in adata.obsm:
        umap_coords = adata.obsm["X_umap"]
        for color_col, title_suffix in [
            ("donor_id", "donor"), ("condition", "condition"),
            ("leiden", "cluster"), ("cell_type", "cell_type"),
        ]:
            if color_col not in adata.obs.columns:
                continue
            fig, ax = plt.subplots(figsize=(10, 8))
            categories = adata.obs[color_col].astype(str).values
            unique_cats = np.unique(categories)
            cmap = plt.cm.get_cmap("tab20", max(len(unique_cats), 1))
            for idx, cat in enumerate(unique_cats):
                mask = categories == cat
                ax.scatter(umap_coords[mask, 0], umap_coords[mask, 1],
                           s=1, alpha=0.3, label=cat, color=cmap(idx), rasterized=True)
            ax.set_xlabel("UMAP1")
            ax.set_ylabel("UMAP2")
            ax.set_title(f"scATAC UMAP - {title_suffix}")
            if len(unique_cats) <= 20:
                ax.legend(markerscale=5, fontsize=7, bbox_to_anchor=(1.05, 1), loc="upper left")
            fig.savefig(os.path.join(qc_dir, f"umap_{title_suffix}.png"), dpi=150, bbox_inches="tight")
            plt.close(fig)
            logger.info("Saved UMAP plot: %s", title_suffix)


# =============================================================================
# Pipeline Steps
# =============================================================================

def step1_import_qc_tile(donors, args, logger):
    """Import fragments into backed h5ad, QC filter, add tile matrix, remove doublets.

    Uses SnapATAC2 backed AnnData (file= param) to preserve fragment file
    references through the entire pipeline. All operations are in-place.

    Returns:
        processed: list of (donor_id, backed_adata) tuples
        qc_df: QC summary DataFrame
        donor_condition_map: dict mapping donor_id -> condition
    """
    logger.info("=" * 60)
    logger.info("STEP 1: Import, QC, tile matrix, doublet removal (backed AnnData)")
    logger.info("=" * 60)

    per_donor_dir = os.path.join(args.output_dir, "per_donor")
    os.makedirs(per_donor_dir, exist_ok=True)

    processed = []
    qc_summary = []
    donor_condition_map = {}

    for donor_id, condition, frag_file in donors:
        logger.info("Processing %s from %s", donor_id, frag_file)
        donor_condition_map[donor_id] = condition

        # Backed h5ad file for this donor
        backing_file = os.path.join(per_donor_dir, f"{donor_id}.h5ad")
        if os.path.exists(backing_file):
            os.remove(backing_file)

        # 1a. Import fragments into backed AnnData (preserves fragment refs)
        adata = snap.pp.import_fragments(
            frag_file,
            chrom_sizes=snap.genome.hg38,
            file=backing_file,
            sorted_by_barcode=False,
        )
        n_raw = adata.n_obs
        logger.info("  %s: %d raw barcodes", donor_id, n_raw)

        # 1b. TSS enrichment (in-place on backed AnnData, needs fragment refs)
        snap.metrics.tsse(adata, gene_anno=snap.genome.hg38)

        # 1c. QC filter using filter_cells (in-place, preserves fragment refs)
        snap.pp.filter_cells(
            adata,
            min_counts=args.min_frags,
            min_tsse=args.min_tsse,
            max_counts=args.max_frags,
        )
        n_after_qc = adata.n_obs
        logger.info("  %s: %d -> %d cells after QC (TSS>=%.1f, frags %d-%d)",
                     donor_id, n_raw, n_after_qc, args.min_tsse, args.min_frags, args.max_frags)

        if n_after_qc < 50:
            logger.warning("  %s: too few cells (%d) - SKIPPING", donor_id, n_after_qc)
            adata.close()
            qc_summary.append({
                "donor_id": donor_id, "condition": condition,
                "n_raw": n_raw, "n_after_qc": n_after_qc,
                "n_doublets_removed": 0, "n_final": n_after_qc,
                "status": "SKIPPED_LOW_CELLS",
            })
            continue

        # 1d. Add tile matrix (populates .X; required before scrublet)
        logger.info("  %s: adding tile matrix (bin_size=%d)...", donor_id, args.tile_size)
        snap.pp.add_tile_matrix(adata, bin_size=args.tile_size)

        # 1e. Doublet detection (scrublet needs .X from tile matrix)
        n_doublets = 0
        try:
            snap.pp.scrublet(adata, features=None)
            n_before = adata.n_obs
            snap.pp.filter_doublets(adata)
            n_doublets = n_before - adata.n_obs
            logger.info("  %s: removed %d doublets (%d remaining)",
                         donor_id, n_doublets, adata.n_obs)
        except Exception as e:
            logger.warning("  %s: doublet removal failed (%s), continuing", donor_id, str(e))

        processed.append((donor_id, adata))
        qc_summary.append({
            "donor_id": donor_id, "condition": condition,
            "n_raw": n_raw, "n_after_qc": n_after_qc,
            "n_doublets_removed": n_doublets,
            "n_final": adata.n_obs, "status": "PASS",
        })

    qc_df = pd.DataFrame(qc_summary)
    logger.info("\nQC Summary:\n%s", qc_df.to_string(index=False))

    return processed, qc_df, donor_condition_map


def step2_create_dataset(processed, output_dir, logger):
    """Create AnnDataSet from per-donor backed AnnDatas.

    AnnDataSet preserves fragment file references from backed AnnDatas,
    enabling make_gene_matrix and macs3 downstream.
    """
    logger.info("=" * 60)
    logger.info("STEP 2: Create AnnDataSet")
    logger.info("=" * 60)

    dataset_file = os.path.join(output_dir, "combined.h5ads")
    if os.path.exists(dataset_file):
        os.remove(dataset_file)

    dataset = snap.AnnDataSet(
        adatas=processed,
        filename=dataset_file,
        add_key="donor_id",
    )
    logger.info("AnnDataSet: %d cells x %d features from %d donors",
                dataset.n_obs, dataset.n_vars, len(processed))
    return dataset


def step3_feature_selection_lsi(dataset, args, logger):
    """Feature selection and spectral embedding (LSI) on AnnDataSet."""
    logger.info("=" * 60)
    logger.info("STEP 3: Feature selection + LSI")
    logger.info("=" * 60)

    snap.pp.select_features(dataset, n_features=args.n_features)
    logger.info("Selected top %d features", args.n_features)

    snap.tl.spectral(dataset)
    logger.info("Spectral embedding (LSI) complete")

    return dataset


def step4_harmony_and_clustering(dataset, donor_condition_map, args, logger):
    """Convert to AnnData, run harmony, then UMAP + Leiden.

    After spectral embedding on AnnDataSet, convert to in-memory AnnData
    for harmony batch correction (via external harmonypy) and clustering.
    """
    logger.info("=" * 60)
    logger.info("STEP 4: Harmony + UMAP + Leiden clustering")
    logger.info("=" * 60)

    logger.info("Converting AnnDataSet to in-memory AnnData...")
    adata = dataset.to_adata()
    # Fix non-unique obs_names (barcodes can collide across donors)
    if not adata.obs_names.is_unique:
        logger.info("Fixing %d duplicate obs_names...",
                     adata.n_obs - adata.obs_names.nunique())
        adata.obs_names_make_unique()
    logger.info("AnnData: %d cells x %d features", adata.n_obs, adata.n_vars)

    # Map condition from donor_id (AnnDataSet add_key column)
    if "donor_id" in adata.obs.columns:
        adata.obs["condition"] = adata.obs["donor_id"].map(donor_condition_map)
        logger.info("Condition mapping:\n%s", adata.obs["condition"].value_counts().to_string())
    else:
        logger.warning("donor_id column not found in obs; condition mapping skipped")

    # Harmony batch correction (external harmonypy; snap.tl.harmony does not exist)
    use_rep = "X_spectral"
    n_donors = adata.obs["donor_id"].nunique() if "donor_id" in adata.obs.columns else 1
    if n_donors > 1:
        try:
            import harmonypy
            X_spectral = adata.obsm["X_spectral"]
            n_comps = min(30, X_spectral.shape[1])
            logger.info("Running harmonypy on %d components across %d donors...",
                        n_comps, n_donors)
            ho = harmonypy.run_harmony(
                X_spectral[:, :n_comps],
                adata.obs,
                "donor_id",
                max_iter_harmony=20,
            )
            adata.obsm["X_spectral_harmony"] = ho.Z_corr.T
            use_rep = "X_spectral_harmony"
            logger.info("Harmony complete. Using embedding: %s", use_rep)
        except Exception as e:
            logger.warning("Harmony failed (%s). Proceeding with uncorrected LSI.", str(e))
    else:
        logger.info("Single donor - skipping harmony")

    # KNN + UMAP + Leiden
    logger.info("Computing nearest neighbors on %s...", use_rep)
    snap.pp.knn(adata, use_rep=use_rep)

    logger.info("Computing UMAP...")
    snap.tl.umap(adata)

    logger.info("Running Leiden clustering (resolution=%.2f)...", args.leiden_resolution)
    snap.tl.leiden(adata, resolution=args.leiden_resolution)

    n_clusters = adata.obs["leiden"].nunique()
    logger.info("Found %d Leiden clusters", n_clusters)
    logger.info("Cluster sizes:\n%s", adata.obs["leiden"].value_counts().sort_index().to_string())

    return adata, use_rep


def step5_cell_type_annotation(adata, dataset, logger):
    """Annotate cell types using gene activity scores from AnnDataSet.

    make_gene_matrix requires AnnDataSet (fragment references) to compute
    gene body accessibility. Scores are mapped to the in-memory AnnData.
    """
    logger.info("=" * 60)
    logger.info("STEP 5: Cell type annotation (gene activity scores)")
    logger.info("=" * 60)

    LIVER_MARKERS = {
        "Hepatocyte": ["ALB", "APOB", "CYP3A4", "CYP2E1", "HNF4A", "PCK1"],
        "Cholangiocyte": ["KRT19", "KRT7", "EPCAM", "SOX9"],
        "Stellate_Cell": ["ACTA2", "COL1A1", "PDGFRB", "DCN", "LUM"],
        "Endothelial": ["PECAM1", "CDH5", "VWF", "ERG"],
        "LSEC": ["CLEC4G", "CLEC4M", "FCN2", "FCN3", "STAB2"],
        "Kupffer_Cell": ["CD68", "MARCO", "TIMD4", "CLEC4F"],
        "Macrophage": ["CD14", "CD163", "CSF1R", "ITGAM"],
        "NK_T_Cell": ["CD3E", "CD3D", "NKG7", "GNLY", "GZMB"],
        "B_Cell": ["CD79A", "MS4A1", "CD19"],
        "Plasma_Cell": ["JCHAIN", "MZB1", "SDC1"],
    }

    try:
        logger.info("Computing gene activity matrix from AnnDataSet...")
        gene_mat = snap.pp.make_gene_matrix(dataset, gene_anno=snap.genome.hg38)
        logger.info("Gene activity matrix: %d cells x %d genes", gene_mat.n_obs, gene_mat.n_vars)

        # Convert backed gene_mat to in-memory if needed
        if hasattr(gene_mat, 'to_memory'):
            gene_mat = gene_mat.to_memory()

        import scipy.sparse as sp
        X = gene_mat.X
        if hasattr(X, 'toarray'):
            # Sparse or backed array - get as dense for scoring
            pass  # keep sparse for efficiency

        if sp.issparse(X):
            row_sums = np.array(X.sum(axis=1)).flatten()
        else:
            row_sums = np.asarray(X.sum(axis=1)).flatten()
        row_sums = np.maximum(row_sums, 1)

        cell_type_scores = pd.DataFrame(index=gene_mat.obs_names)
        gene_names = list(gene_mat.var_names)

        for ct, markers in LIVER_MARKERS.items():
            present = [m for m in markers if m in gene_names]
            if not present:
                logger.warning("  No markers found for %s", ct)
                continue
            marker_idx = [gene_names.index(m) for m in present]
            if sp.issparse(X):
                scores = np.array(X[:, marker_idx].sum(axis=1)).flatten()
            else:
                scores = np.asarray(X[:, marker_idx].sum(axis=1)).flatten()
            cell_type_scores[ct] = scores / row_sums
            logger.info("  %s: %d/%d markers found", ct, len(present), len(markers))

        if cell_type_scores.shape[1] > 0:
            ct_assignments = cell_type_scores.idxmax(axis=1)
            # Map from gene_mat obs_names to adata obs_names
            adata.obs["cell_type"] = ct_assignments.reindex(adata.obs_names).values
            adata.obs["cell_type"] = adata.obs["cell_type"].fillna("Unknown")
            logger.info("Cell type counts:\n%s", adata.obs["cell_type"].value_counts().to_string())
        else:
            raise ValueError("No marker genes scored")

        del gene_mat
        gc.collect()

    except Exception as e:
        logger.warning("Gene activity annotation failed: %s", str(e))
        logger.info("Using Leiden clusters as cell type labels (fallback)")
        adata.obs["cell_type"] = "cluster_" + adata.obs["leiden"].astype(str)

    return adata


def step6_peak_calling(adata, dataset, output_dir, logger):
    """Call peaks using MACS3 via AnnDataSet (needs fragment references).

    Calls peaks on all cells (unified peak set). Per-cell-type peak calling
    requires setting groupby on AnnDataSet obs, which may not be mutable.
    """
    logger.info("=" * 60)
    logger.info("STEP 6: Peak calling (MACS3)")
    logger.info("=" * 60)

    peak_dir = os.path.join(output_dir, "cell_type_peak_sets")
    os.makedirs(peak_dir, exist_ok=True)

    # Try per-cell-type peaks first, fall back to unified
    groupby_col = None
    try:
        dataset.obs["cell_type"] = adata.obs["cell_type"].values
        groupby_col = "cell_type"
        logger.info("Set cell_type on AnnDataSet for per-cell-type peak calling")
    except Exception:
        try:
            dataset.obs["leiden"] = adata.obs["leiden"].values
            groupby_col = "leiden"
            logger.info("Set leiden on AnnDataSet for per-cluster peak calling")
        except Exception:
            logger.info("Cannot set groupby on AnnDataSet; calling unified peaks")

    try:
        logger.info("Running MACS3 (groupby=%s)...", groupby_col)
        peak_result = snap.tl.macs3(
            dataset,
            groupby=groupby_col,
            qvalue=0.05,
            shift=-100,
            extsize=200,
        )
        logger.info("MACS3 peak calling complete")

        # Export peak BED files (macs3 returns dict of polars DataFrames or stores in uns)
        if peak_result is not None:
            peaks_data = peak_result
        elif "macs3" in dataset.uns:
            peaks_data = dataset.uns["macs3"]
        else:
            peaks_data = None

        if peaks_data and isinstance(peaks_data, dict):
            for group_name, peaks_pl in peaks_data.items():
                # Convert polars to pandas if needed
                if hasattr(peaks_pl, 'to_pandas'):
                    peaks_df = peaks_pl.to_pandas()
                else:
                    peaks_df = peaks_pl
                if len(peaks_df) > 0:
                    bed_path = os.path.join(peak_dir, f"{group_name}_peaks.bed")
                    peaks_df.iloc[:, :3].to_csv(bed_path, sep="\t", header=False, index=False)
                    logger.info("  %s: %d peaks -> %s", group_name, len(peaks_df), bed_path)

        return adata, True

    except Exception as e:
        logger.error("MACS3 peak calling failed: %s", str(e))
        return adata, False


def step7_differential_accessibility(adata, output_dir, logger):
    """Differential accessibility: MASLD vs Normal per cell type.

    diff_test API (v2.8): takes cell_group1/cell_group2 as list[str] (cell names)
    or list[int] (indices). Returns polars DataFrame.
    """
    logger.info("=" * 60)
    logger.info("STEP 7: Differential accessibility (MASLD vs Normal)")
    logger.info("=" * 60)

    conditions = adata.obs["condition"].unique().tolist()
    logger.info("Conditions present: %s", conditions)

    masld_labels = [c for c in conditions
                    if str(c).upper() in ["MASLD", "NASH", "NAFLD", "NAFL", "MASH", "MASL",
                                           "DISEASE", "STEATOSIS"]]
    normal_labels = [c for c in conditions
                     if str(c).upper() in ["NORMAL", "HEALTHY", "CONTROL"]]

    if not masld_labels or not normal_labels:
        logger.warning("Cannot identify MASLD and Normal groups from: %s", conditions)
        return None

    logger.info("MASLD group: %s, Normal group: %s", masld_labels, normal_labels)

    cell_types = adata.obs["cell_type"].unique().tolist()
    all_da_results = []

    for ct in cell_types:
        ct_mask = adata.obs["cell_type"] == ct
        n_ct = int(ct_mask.sum())
        if n_ct < 20:
            logger.warning("  %s: only %d cells - skipping", ct, n_ct)
            continue

        masld_mask = ct_mask & adata.obs["condition"].isin(masld_labels)
        normal_mask = ct_mask & adata.obs["condition"].isin(normal_labels)

        n_masld = int(masld_mask.sum())
        n_normal = int(normal_mask.sum())
        if n_masld < 5 or n_normal < 5:
            logger.warning("  %s: insufficient cells (MASLD=%d, Normal=%d) - skipping",
                           ct, n_masld, n_normal)
            continue

        logger.info("  %s: %d cells (MASLD=%d, Normal=%d)", ct, n_ct, n_masld, n_normal)

        try:
            # diff_test requires list[str] cell names (NOT boolean masks)
            masld_cells = adata.obs_names[masld_mask].tolist()
            normal_cells = adata.obs_names[normal_mask].tolist()

            da_result = snap.tl.diff_test(
                adata,
                cell_group1=masld_cells,
                cell_group2=normal_cells,
            )

            # diff_test returns polars DataFrame
            if hasattr(da_result, 'to_pandas'):
                da_df = da_result.to_pandas()
            else:
                da_df = da_result

            da_df["cell_type"] = ct
            all_da_results.append(da_df)

            # Report significant DA regions
            padj_col = None
            for col in ["adjusted p-value", "adjusted_p_value", "padj", "fdr",
                         "adjusted p-value (BHFDR)"]:
                if col in da_df.columns:
                    padj_col = col
                    break
            if padj_col:
                n_sig = int((da_df[padj_col] < 0.05).sum())
                logger.info("  %s: %d DA regions (padj < 0.05)", ct, n_sig)

        except Exception as e:
            logger.error("  %s: DA test failed: %s", ct, str(e))
            continue

    if all_da_results:
        da_combined = pd.concat(all_da_results, ignore_index=True)
        da_path = os.path.join(output_dir, "scatac_da_results.csv")
        da_combined.to_csv(da_path, index=False)
        logger.info("Saved DA results: %d rows -> %s", len(da_combined), da_path)
        return da_combined
    else:
        logger.warning("No DA results generated.")
        return None


# =============================================================================
# Main
# =============================================================================

def main():
    args = parse_args()
    args.input_dir = os.path.abspath(args.input_dir)
    args.output_dir = os.path.abspath(args.output_dir)
    args.sample_csv = os.path.abspath(args.sample_csv)

    os.makedirs(args.output_dir, exist_ok=True)
    os.makedirs(os.path.join(args.output_dir, "qc"), exist_ok=True)
    os.makedirs(os.path.join(args.output_dir, "checkpoints"), exist_ok=True)
    os.makedirs(os.path.join(args.output_dir, "cell_type_peak_sets"), exist_ok=True)

    logger = setup_logging(args.output_dir)
    logger.info("=" * 60)
    logger.info("SnapATAC2 scATAC-seq Processing Pipeline")
    logger.info("  GSE244832 Human Liver (combinatorial indexing)")
    logger.info("  SnapATAC2 version: %s", snap.__version__)
    logger.info("=" * 60)
    logger.info("Parameters:")
    for k, v in vars(args).items():
        logger.info("  %-20s = %s", k, v)

    try:
        # Load metadata
        sample_df = load_sample_metadata(args.sample_csv)
        logger.info("Loaded %d donors. Conditions: %s",
                    len(sample_df), sample_df["condition"].value_counts().to_dict())

        donors_info = discover_donors(args.input_dir, sample_df, logger)
        if not donors_info:
            logger.error("No fragment files found in %s", args.input_dir)
            sys.exit(1)
        logger.info("Found %d donors with fragment files", len(donors_info))

        # Step 1: Import, QC, tile matrix, doublet removal (per-donor backed AnnData)
        processed, qc_df, donor_condition_map = step1_import_qc_tile(donors_info, args, logger)
        if not processed:
            logger.error("No donors passed QC. Exiting.")
            sys.exit(1)
        qc_df.to_csv(os.path.join(args.output_dir, "qc", "qc_summary.csv"), index=False)
        total_cells = sum(a.n_obs for _, a in processed)
        logger.info("Total cells after QC + doublet removal: %d across %d donors",
                     total_cells, len(processed))

        # Step 2: Create AnnDataSet (preserves fragment refs for gene activity + peaks)
        dataset = step2_create_dataset(processed, args.output_dir, logger)

        # Step 3: Feature selection + LSI on AnnDataSet
        dataset = step3_feature_selection_lsi(dataset, args, logger)

        # Step 4: Harmony + UMAP + Leiden (converts to in-memory AnnData)
        adata, use_rep = step4_harmony_and_clustering(
            dataset, donor_condition_map, args, logger
        )

        # Checkpoint: save after clustering
        ckpt_path = os.path.join(args.output_dir, "checkpoints", "after_clustering.h5ad")
        logger.info("Saving checkpoint: %s", ckpt_path)
        adata.write(ckpt_path)

        # Step 5: Cell type annotation (uses AnnDataSet for gene activity)
        adata = step5_cell_type_annotation(adata, dataset, logger)

        ckpt_path = os.path.join(args.output_dir, "checkpoints", "after_annotation.h5ad")
        logger.info("Saving checkpoint: %s", ckpt_path)
        adata.write(ckpt_path)

        # Step 6: Peak calling (uses AnnDataSet for fragment access)
        adata, peaks_ok = step6_peak_calling(adata, dataset, args.output_dir, logger)

        # Step 7: Differential accessibility
        if not args.skip_da:
            step7_differential_accessibility(adata, args.output_dir, logger)

        # Close AnnDataSet and per-donor files
        try:
            dataset.close()
        except Exception:
            pass
        for _, ad_obj in processed:
            try:
                ad_obj.close()
            except Exception:
                pass

        # Save final AnnData
        final_path = os.path.join(args.output_dir, "snapatac2_processed.h5ad")
        logger.info("Saving final AnnData: %s", final_path)
        adata.write(final_path)

        # QC plots
        plot_qc(adata, args.output_dir, logger)

        # Summary
        summary = {
            "timestamp": datetime.now().isoformat(),
            "snapatac2_version": snap.__version__,
            "n_donors_input": len(donors_info),
            "n_donors_pass_qc": len([r for r in qc_df.to_dict("records") if r["status"] == "PASS"]),
            "n_cells_total": int(adata.n_obs),
            "n_clusters": int(adata.obs["leiden"].nunique()),
            "cell_types": adata.obs.get("cell_type", pd.Series()).value_counts().to_dict()
                          if "cell_type" in adata.obs.columns else {},
            "parameters": {k: str(v) for k, v in vars(args).items()},
        }
        with open(os.path.join(args.output_dir, "run_summary.json"), "w") as f:
            json.dump(summary, f, indent=2, default=str)

        logger.info("=" * 60)
        logger.info("Pipeline COMPLETE")
        logger.info("  Total cells: %d", adata.n_obs)
        logger.info("  Clusters: %d", adata.obs["leiden"].nunique())
        if "cell_type" in adata.obs.columns:
            logger.info("  Cell types: %d", adata.obs["cell_type"].nunique())
        logger.info("  Output: %s", args.output_dir)
        logger.info("=" * 60)

    except Exception as e:
        logger.error("Pipeline FAILED: %s", str(e), exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
