suppressPackageStartupMessages({library(readxl); library(data.table)})
cat("RRHO2 installed:", requireNamespace("RRHO2", quietly=TRUE), "\n")
cat("RRHO installed:", requireNamespace("RRHO", quietly=TRUE), "\n")
BASE <- Sys.getenv("MASLD_PROJECT_ROOT")
s4 <- as.data.table(read_excel(file.path(BASE,"data/external/vacca_2024/42255_2024_1043_MOESM4_ESM.xlsx"), sheet="Table S4"))
cat("=== S4 dims:", paste(dim(s4),collapse=" x "), "===\n")
cat("=== first 12 colnames ===\n"); print(head(names(s4),12))
hc <- grep("UCAM|VCU|EPoS|Severe|Mild|Moderate", names(s4), value=TRUE)
cat("=== human-progression L2FC cols ===\n"); print(hc)
cat("=== Gene/DSEA cols ===\n"); print(grep("Gene|ENSG|DSEA|stage", names(s4), value=TRUE, ignore.case=TRUE))
# our per-gene concordance file
g <- fread(file.path(BASE,"Analysis/Cross_Species_Concordance/results/gene_concordance_per_gene.csv"))
cat("=== per_gene nrow:", nrow(g), " unique human_symbol:", length(unique(g$human_symbol)), "===\n")
cat("translatability_score present in atlas? checking unified...\n")
u <- fread(file.path(BASE,"Analysis/Cross_Species_Concordance/results/concordance_atlas_unified.csv"))
cat("unified nrow:", nrow(u), " translatability_score summary:\n"); print(summary(u$translatability_score))
cat("score_gene summary:\n"); print(summary(u$score_gene))
cat("mean_h_lfc summary:\n"); print(summary(u$mean_h_lfc))
cat("n_concordant table:\n"); print(table(u$n_concordant))
cat("primary_category table:\n"); print(table(u$primary_category))
