name: music_deconv
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.3
  - r-devtools
  - r-remotes
  - r-seurat
  - r-seuratobject
  - r-matrix
  - r-data.table
  - r-dplyr
  - r-tidyr
  - r-ggplot2
  - r-patchwork
  - r-ggrepel
  - r-future
  - r-qs
  - bioconductor-singlecellexperiment
  - bioconductor-summarizedexperiment
  - bioconductor-biobase
  - bioconductor-scater
  - bioconductor-scran
  - bioconductor-biocparallel
  - bioconductor-delayedarray
  - bioconductor-biocsingular
  - bioconductor-annotationdbi
  - bioconductor-org.mm.eg.db
  - bioconductor-org.hs.eg.db
  - python=3.11
  - scanpy
  - anndata
  - scvi-tools
  - pytorch
  - torchvision
  - torchaudio
  - leidenalg
  - igraph
  - umap-learn
  - pynndescent
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - pip
  - pip:
      - celltypist
