##############################################################################
# fig5_panel_orthogonality.R — Supplement figS08 (was Fig 5 PANEL 5c)
#
# DEMOTED to supplement 2026-06-18: the main Fig 5 5c slot now carries the
# drug-target orthogonality landscape (drug_target_orthogonality_landscape.R).
# This evidence-layer correlation heatmap moves to figS08_subtyping_convergence
# but keeps the |rho| <= 0.18 independence claim that the Results cite.
#
# Evidence-layer orthogonality heatmap. Pairwise Spearman correlation between
# the 7 atlas evidence layers shows the layers carry near-independent signal
# (max off-diagonal |rho| = 0.18). This is the "convergence is rare by design"
# panel: because the modalities are orthogonal, a gene scoring across many of
# them is genuinely multi-evidence rather than one signal counted repeatedly.
#
# Data: RNA-seq/results/multi_evidence/atlas_layer_correlations.csv
#   (generated by RNA-seq/27a_assemble_evidence_atlas.R; long format
#    Layer1, Layer2, Correlation).
#
# Output: $FIGS08_DIR/evidence_layer_independence.pdf
##############################################################################

suppressPackageStartupMessages({
  library(data.table)
  library(ggplot2)
  library(scales)
})

BASE <- Sys.getenv("MASLD_PROJECT_ROOT",
  "/gpfs/commons/groups/sanjana_lab/Cas13/MASLD_library_design")
source(file.path(BASE, "scripts/figures/publication_theme.R"))
source(file.path(BASE, "scripts/figures/load_figure_data.R"))

OUTDIR <- FIGS08_DIR
dir.create(OUTDIR, recursive = TRUE, showWarnings = FALSE)

# ---------------------------------------------------------------------------
# Load layer correlations
# ---------------------------------------------------------------------------
corr <- load_layer_correlations()
stopifnot(!is.null(corr))

# Readable layer labels (order = atlas L1..L7).
lab_map <- c(
  L1_Human_DE    = "Human DE",
  L2_Mouse_DE    = "Mouse DE",
  L3_Concordance = "Concordance",
  L4_Causal      = "Genetic causal",
  L5_Sex         = "Sex",
  L6_Pathway     = "Pathway",
  L7_Safety      = "Safety"
)
lev <- names(lab_map)

corr <- corr[Layer1 %in% lev & Layer2 %in% lev]
corr[, L1 := factor(lab_map[Layer1], levels = lab_map[lev])]
corr[, L2 := factor(lab_map[Layer2], levels = rev(lab_map[lev]))]

# Lower-triangle only (incl diagonal) for a clean read; blank the rest.
idx1 <- match(as.character(corr$L1), lab_map[lev])
idx2 <- match(as.character(corr$L2), rev(lab_map[lev]))
# Keep cells where column index <= row index in the displayed orientation.
corr[, keep := match(as.character(L1), lab_map[lev]) <=
                (length(lev) + 1 - match(as.character(L2), rev(lab_map[lev])))]
corr_show <- corr[keep == TRUE]

# Max off-diagonal |rho| for the subtitle (honest headline number).
max_off <- corr[Layer1 != Layer2, max(abs(Correlation), na.rm = TRUE)]
cat(sprintf("Max off-diagonal |rho| = %.3f\n", max_off))

# Label formatting: show diagonal as 1; off-diagonal to 2 dp.
corr_show[, is_diag := Layer1 == Layer2]
corr_show[, lab := ifelse(is_diag, "1", sprintf("%.2f", Correlation))]

# ---------------------------------------------------------------------------
# Panel 5c — lower-triangle Spearman correlation heatmap
# Diverging fill centered at 0; symmetric limits so weak correlations read
# as near-white. Magenta(+) / blue(-) per house diverging palette.
# ---------------------------------------------------------------------------
p5c <- ggplot(corr_show, aes(x = L1, y = L2, fill = Correlation)) +
  geom_tile(color = "white", linewidth = 0.6) +
  geom_text(aes(label = lab,
                color = abs(Correlation) > 0.6 | is_diag),
            size = 1.9, family = "Helvetica", show.legend = FALSE) +
  scale_color_manual(values = c(`TRUE` = "white", `FALSE` = "grey20")) +
  scale_fill_gradient2(low = masld_colors$down, mid = "white",
                       high = masld_colors$up, midpoint = 0,
                       limits = c(-1, 1), breaks = c(-1, -0.5, 0, 0.5, 1),
                       name = expression(Spearman~rho)) +
  coord_equal() +
  # PI directive (2026-06-11): short single title line only. The honest
  # headline number (max off-diagonal |rho| = 0.18) is printed to stdout for
  # the figure caption — NOT annotated on the panel.
  labs(x = NULL, y = NULL,
       title = "Evidence-layer correlations") +
  theme_masld(base_size = 7) +
  theme(plot.title = element_text(face = "bold", size = 8),
        plot.subtitle = element_text(size = 6.3, color = "grey30"),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 6.2),
        axis.text.y = element_text(size = 6.2),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        legend.key.height = unit(0.45, "cm"),
        legend.key.width = unit(0.22, "cm"),
        legend.title = element_text(size = 6))

ggsave(file.path(OUTDIR, "evidence_layer_independence.pdf"), p5c,
       width = 3.6, height = 3.3, device = cairo_pdf)
cat("Saved: figS08_subtyping_convergence/evidence_layer_independence.pdf\n")

cat("\nDONE.\n")
