##############################################################################
# Supplementary Figure: Published DEG Validation
#   (a) DEG recovery rate by matched contrast (dot plot)
#   (b) Recovery counts (stacked bars)
#   (c) LFC concordance scatter grid (10 facets)
#   (d) Volcano plot of main dream mega-analysis (MASLD vs Control)
#
# Data generated by published_deg_comparison.py → loaded as CSVs
##############################################################################

suppressPackageStartupMessages({
  library(ggplot2)
  library(patchwork)
  library(data.table)
  library(scales)
  library(ggrepel)
})

set.seed(42)

BASE <- Sys.getenv("MASLD_PROJECT_ROOT",
                   "/gpfs/commons/groups/sanjana_lab/Cas13/MASLD_library_design")
source(file.path(BASE, "scripts/figures/publication_theme.R"))
source(file.path(BASE, "scripts/figures/load_figure_data.R"))

OUT       <- file.path(FIGS02_DIR, "figS_deg_validation.pdf")
PANEL_DIR <- file.path(FIGS02_DIR, "panels")
dir.create(PANEL_DIR, showWarnings = FALSE, recursive = TRUE)

# Pre-initialize
p_a <- placeholder("Panel a: DEG recovery rate")
p_b <- placeholder("Panel b: Recovery counts")
p_c <- placeholder("Panel c: LFC concordance")

# Contrast colors (consistent with published_deg_comparison.py)
contrast_bg <- c(
  "Disease vs Control" = "#E3F2FD",
  "NASH vs NAFL"       = "#F3E5F5",
  "Adv vs Early Fib"   = "#E0F2F1"
)
source_colors <- c(
  "Published"          = "#1565C0",
  "Published (ordinal)" = "#1565C0",
  "Reproduced (DESeq2)" = "#00695C",
  "Per-study (limma)"  = "#C2185B"
)

# ==========================================================================
# Load Python-generated CSVs
# ==========================================================================
summary_path <- file.path(FIG_OUT, "published_deg_comparison_summary.csv")
lfc_path     <- file.path(FIG_OUT, "published_deg_lfc_pairs.csv")

if (file.exists(summary_path) && file.exists(lfc_path)) {
  deg_summary <- fread(summary_path)
  lfc_pairs   <- fread(lfc_path)

  # Sort by contrast group, then by n_samples
  contrast_order <- c("Disease vs Control" = 1, "NASH vs NAFL" = 2, "Adv vs Early Fib" = 3)
  deg_summary[, contrast_rank := contrast_order[contrast]]
  deg_summary <- deg_summary[order(contrast_rank, n_samples)]
  deg_summary[, label_full := paste0(label, " (n=", n_samples, ")")]
  deg_summary[, label_full := factor(label_full, levels = label_full)]

  # ========================================================================
  # Panel (a): Recovery rate dot plot — grouped by contrast
  # ========================================================================
  group_bounds <- deg_summary[, .(ymin = min(as.numeric(label_full)) - 0.45,
                                   ymax = max(as.numeric(label_full)) + 0.45),
                               by = contrast]

  p_a <- ggplot(deg_summary) +
    geom_rect(data = group_bounds,
              aes(xmin = -Inf, xmax = Inf, ymin = ymin, ymax = ymax, fill = contrast),
              alpha = 0.25, inherit.aes = FALSE) +
    scale_fill_manual(values = contrast_bg, guide = "none") +
    ggnewscale::new_scale_fill() +
    geom_segment(aes(x = pct_meta, xend = pct_mega,
                     y = label_full, yend = label_full),
                 color = "#9E9E9E", linewidth = 0.4, alpha = 0.6) +
    geom_point(aes(x = pct_mega, y = label_full, size = n_study_degs,
                   color = source), alpha = 0.85, shape = 16) +
    geom_point(aes(x = pct_meta, y = label_full, color = source),
               size = 1.5, shape = 18, alpha = 0.7) +
    geom_text(aes(x = pmax(pct_mega, pct_meta) + 3, y = label_full,
                  label = format(n_study_degs, big.mark = ",")),
              size = 1.7, color = "#616161", hjust = 0) +
    geom_vline(xintercept = median(deg_summary$pct_mega),
               linetype = "dashed", linewidth = 0.4, color = "#880E4F", alpha = 0.4) +
    scale_color_manual(values = source_colors, name = NULL) +
    scale_size_continuous(range = c(1.5, 7), guide = "none") +
    scale_x_continuous(limits = c(-3, 108), breaks = seq(0, 100, 25)) +
    labs(x = "% Study DEGs recovered (padj < 0.1)", y = NULL,
         title = "DEG recovery by matched contrast") +
    theme_masld() +
    theme(legend.position = "bottom",
          legend.key.size = unit(0.2, "cm"),
          legend.text = element_text(size = 5),
          axis.text.y = element_text(size = 6),
          plot.title = element_text(size = 7))

  # ========================================================================
  # Panel (b): Stacked recovery bars
  # ========================================================================
  deg_stack <- melt(deg_summary,
                    id.vars = c("dataset", "label", "label_full", "contrast", "contrast_rank",
                                "n_samples", "n_study_degs", "pct_mega"),
                    measure.vars = c("n_recovered_mega", "n_meta_only", "n_not_recovered"),
                    variable.name = "category", value.name = "n_genes")
  deg_stack[, category := factor(category,
                                  levels = c("n_recovered_mega", "n_meta_only", "n_not_recovered"),
                                  labels = c("In mega", "In meta only", "Not recovered"))]

  deg_summary_f <- copy(deg_summary)
  deg_summary_f[, label_f := factor(label, levels = label)]
  deg_stack[, label_f := factor(label, levels = levels(deg_summary_f$label_f))]

  p_b <- ggplot(deg_stack, aes(x = n_genes, y = label_f, fill = category)) +
    geom_col(width = 0.6) +
    geom_text(data = deg_summary_f,
              aes(x = n_study_degs, y = label_f,
                  label = sprintf("%.0f%%", pct_mega), fill = NULL),
              hjust = -0.15, size = 2, fontface = "bold", color = "#0D47A1") +
    scale_fill_manual(values = c("In mega" = "#0D47A1",
                                  "In meta only" = "#7B1FA2",
                                  "Not recovered" = "#BDBDBD"),
                       name = NULL) +
    scale_x_continuous(expand = expansion(mult = c(0, 0.15)),
                       labels = comma) +
    labs(x = "Number of DEGs", y = NULL, title = "Recovery counts") +
    theme_masld() +
    theme(legend.position = "bottom",
          legend.key.size = unit(0.2, "cm"),
          legend.text = element_text(size = 5),
          axis.text.y = element_text(size = 6),
          plot.title = element_text(size = 7))

  # ========================================================================
  # Panel (c): LFC concordance scatter grid — faceted, 2 rows x 5 cols
  # ========================================================================
  label_order <- deg_summary$label
  lfc_pairs[, label := factor(label, levels = label_order)]
  lfc_pairs[, concordant := sign(pub_lfc) == sign(mega_lfc)]

  lfc_stats <- lfc_pairs[, .(
    r = cor(pub_lfc, mega_lfc, use = "complete.obs"),
    dir_pct = 100 * sum(concordant) / .N,
    n = .N
  ), by = .(label, contrast)]

  p_c <- ggplot(lfc_pairs, aes(x = pub_lfc, y = mega_lfc)) +
    rasterize_layer(
      geom_point(aes(color = concordant), size = 0.15, alpha = 0.12, shape = 16)
    ) +
    geom_abline(slope = 1, intercept = 0, color = "gray60", linewidth = 0.3) +
    geom_hline(yintercept = 0, color = "gray85", linewidth = 0.2) +
    geom_vline(xintercept = 0, color = "gray85", linewidth = 0.2) +
    scale_color_manual(values = c("TRUE" = "#0D47A1", "FALSE" = "#C2185B"),
                       guide = "none") +
    geom_text(data = lfc_stats,
              aes(x = -Inf, y = Inf, label = sprintf("r=%.2f", r)),
              hjust = -0.1, vjust = 1.3, size = 2.2, fontface = "bold",
              color = "#0D47A1", inherit.aes = FALSE) +
    geom_text(data = lfc_stats,
              aes(x = -Inf, y = Inf, label = sprintf("%.0f%% concordant", dir_pct)),
              hjust = -0.1, vjust = 2.8, size = 1.8,
              color = "#757575", inherit.aes = FALSE) +
    facet_wrap(~label, nrow = 2, ncol = 5, scales = "free") +
    labs(x = expression(Study~log[2]~FC), y = expression(Mega~log[2]~FC),
         title = "LFC concordance (study vs matched mega-analysis)") +
    theme_masld() +
    theme(strip.text = element_text(size = 5.5, face = "bold"),
          axis.text = element_text(size = 4.5),
          axis.title = element_text(size = 6),
          plot.title = element_text(size = 7))

} else {
  message("WARNING: Published DEG comparison CSVs not found. Run published_deg_comparison.py first.")
}

# ==========================================================================
# Panel (d): Volcano plot — Dream mega-analysis (MASLD vs Control)
# ==========================================================================
p_d <- placeholder("Panel d: Dream volcano")

dream <- load_dream_results()
if (!is.null(dream)) {
  dream[, neg_log10_padj := -log10(pmin(dream_padj, 1))]
  # Cap at 50 (max observed ~47)
  padj_cap <- 50
  dream[neg_log10_padj > padj_cap, neg_log10_padj := padj_cap]

  dream[, sig := fifelse(dream_padj < 0.1 & abs(dream_logFC) > 0.5,
                          fifelse(dream_logFC > 0, "Up", "Down"), "NS")]

  n_up   <- sum(dream$sig == "Up", na.rm = TRUE)
  n_down <- sum(dream$sig == "Down", na.rm = TRUE)
  n_total <- nrow(dream)

  # Tight LFC range for compact display
  lfc_cap <- 4
  dream[, logFC_plot := pmin(pmax(dream_logFC, -lfc_cap), lfc_cap)]

  # Label top 5 genes per direction (by rank score = |LFC| * -log10p)
  dream[, rank_score := abs(dream_logFC) * neg_log10_padj]
  top_genes <- rbind(
    dream[sig == "Up"][order(-rank_score)][1:min(5, sum(dream$sig == "Up"))],
    dream[sig == "Down"][order(-rank_score)][1:min(5, sum(dream$sig == "Down"))]
  )

  subtitle_text <- "padj < 0.1, |log2FC| > 0.5"

  p_d <- ggplot(dream, aes(x = logFC_plot, y = neg_log10_padj, color = sig)) +
    rasterize_layer(
      geom_point(size = 0.1, alpha = 0.15, shape = 16)
    ) +
    scale_color_manual(values = c(Down = masld_colors$down,
                                  NS   = masld_colors$ns,
                                  Up   = masld_colors$up),
                       name = NULL) +
    geom_text_repel(data = top_genes,
                    aes(label = symbol),
                    size = 2.0, max.overlaps = 15,
                    segment.size = 0.15, min.segment.length = 0,
                    fontface = "italic", force = 2, box.padding = 0.12) +
    geom_vline(xintercept = c(-0.5, 0.5), linetype = "dashed",
               linewidth = 0.25, color = "gray60") +
    geom_hline(yintercept = -log10(0.1), linetype = "dashed",
               linewidth = 0.25, color = "gray60") +
    coord_cartesian(xlim = c(-lfc_cap, lfc_cap)) +
    labs(x = expression(log[2]~FC), y = expression(-log[10]~padj),
         title = "MASLD vs Control", subtitle = subtitle_text) +
    theme_masld() +
    theme(legend.position = "none",
          plot.title = element_text(size = 7),
          plot.subtitle = element_text(size = 5.5),
          axis.title = element_text(size = 6),
          axis.text = element_text(size = 5.5),
          plot.margin = margin(1, 1, 1, 1))
} else {
  message("WARNING: dream_results.csv not found, skipping volcano panel")
}

# ==========================================================================
# Save individual panels
# ==========================================================================
save_fig(p_a, file.path(PANEL_DIR, "panel_a_deg_recovery.pdf"),
         width = fig_full_width * 0.65, height = 3.5)
save_fig(p_b, file.path(PANEL_DIR, "panel_b_recovery_counts.pdf"),
         width = fig_full_width * 0.35, height = 3.5)
save_fig(p_c, file.path(PANEL_DIR, "panel_c_lfc_concordance.pdf"),
         width = fig_full_width, height = 3.5)
save_fig(p_d, file.path(PANEL_DIR, "panel_d_volcano.pdf"),
         width = fig_half_width * 0.85, height = 2.5)
message("Individual panels saved to ", PANEL_DIR)

# ==========================================================================
# Assemble: 3 rows
#   Row 1: A A A A B B     recovery rate (4/6) | stacked bars (2/6)
#   Row 2: C C C C C C     LFC grid (full width)
#   Row 3: D D D . . .     Volcano (half width)
# ==========================================================================
design <- "
AAAABB
CCCCCC
DDD...
"

figS1 <- p_a + p_b + p_c + p_d +
  plot_layout(design = design, heights = c(1.2, 1.0, 0.7)) +
  plot_annotation(tag_levels = "a") &
  theme(plot.tag = element_text(size = 8, face = "bold"))

save_fig(figS1, OUT, height = 8.5)
message("Fig S1 saved to ", OUT)
