#!/usr/bin/env Rscript
# stagedeg_carrier_routing.R
# Fig S3 (supplementary; demoted from main 2026-07-02 in the A-J layout —
# overlaps panel 3F's cell-type composition track) — stage-DEG carrier routing
# across the fibrosis cascade.
# For each CRN transition (F0->F1 ... F3->F4), the relative share of that
# transition's bulk stage-DEGs that is INTRINSICALLY carried by each cell type
# (concordant within-cell-type stage effect, strong+likely). Hepatocytes (gray)
# are present throughout but the F2->F3 fibrosis inflection is dominated by
# non-parenchymal carriers (endothelial, cholangiocyte, fibroblast) — the
# multi-cellular carrier shift.
#
# Complements Fig 3C (which plots cell-type *composition* / who is present);
# this panel plots DEG *carrier attribution* (who carries the change).
#
# RIGOR (per plan): documented (Andrews n=58) F-stage arm — routing_summary is
# regenerated by WS3_01 reading per_celltype_per_transition_logFC_documented.csv
# (NOT the forbidden augmented/scVI arm; the fine arm is stored under the legacy
# axis label "augmented"). This is the ONE main stage panel on documented Kleiner
# F-stage rather than coarse; it is real recorded F-stage, not scVI-inferred.
# F3->F4 is flagged low-power (n=58). Never uses routing_hep_vs_nonhep_share.csv
# or signed LIANA.
#
# Output (PDF only): FIG2_DIR/panels/fig3d_stagedeg_carrier_routing.pdf
# Sidecar: FIG2_DIR/panels/data/stagedeg_carrier_routing.csv

suppressPackageStartupMessages({
  library(data.table)
  library(ggplot2)
  library(scales)
})

BASE <- Sys.getenv("MASLD_PROJECT_ROOT",
                   unset = "/gpfs/commons/groups/sanjana_lab/Cas13/MASLD_library_design")
source(file.path(BASE, "scripts/figures/publication_theme.R"))
source(file.path(BASE, "scripts/figures/load_figure_data.R"))

PANEL_DIR <- file.path(FIG2_DIR, "panels")
DATA_DIR  <- file.path(PANEL_DIR, "data")
dir.create(DATA_DIR, showWarnings = FALSE, recursive = TRUE)

ROUT <- file.path(BASE,
  "Analysis/SingleCell/results_gpu_v2/disease_signatures/stagedeg_routing")

# ── Data: documented fine arm (axis label "augmented"), fine F0->F4 ───────────
es <- fread(file.path(ROUT, "routing_summary_by_transition.csv"))
es <- es[axis == "augmented" &
         stage_set %in% c("fine_F0_F1", "fine_F1_F2", "fine_F2_F3", "fine_F3_F4")]
es[, n_intrinsic := n_intrinsic_strong + n_intrinsic_likely]

# Display labels for the carriers that appear on the fine arm.
disp_map <- c(Hepatocytes = "Hepatocytes", Cholangiocytes = "Cholangiocytes",
              Endothelial = "Endothelial cells", Fibroblasts = "Fibroblasts",
              Macrophages = "Macrophages", T_cells = "T cells",
              B_cells = "B cells", Resident_NK = "Resident NK", Plasma = "Plasma cells")
es[, ct_disp := disp_map[cell_type]]

# Drop lineages that carry nothing on this axis (declutter legend).
keep <- es[, .(tot = sum(n_intrinsic)), by = ct_disp][tot > 0, ct_disp]
es <- es[ct_disp %in% keep]

# Relative composition per transition (genuine partition — intrinsic counts).
es[, frac := n_intrinsic / sum(n_intrinsic), by = stage_set]
es[, trans_lab := factor(fcase(
      stage_set == "fine_F0_F1", "F0→F1", stage_set == "fine_F1_F2", "F1→F2",
      stage_set == "fine_F2_F3", "F2→F3", stage_set == "fine_F3_F4", "F3→F4"),
      levels = c("F0→F1", "F1→F2", "F2→F3", "F3→F4"))]

# Colours: hepatocytes forced gray (house convention -> displacement pops);
# non-parenchymal from the shared ct_palette. Stack hepatocytes at the bottom.
ct_col <- c("Hepatocytes"       = "#9E9E9E",
            "Cholangiocytes"    = unname(ct_palette["Cholangiocytes"]),
            "Endothelial cells" = unname(ct_palette["Endothelial cells"]),
            "Fibroblasts"       = unname(ct_palette["Fibroblasts"]),
            "Macrophages"       = unname(ct_palette["Macrophages"]),
            "T cells"           = unname(ct_palette["T cells"]))
stack_levels <- c("T cells", "Macrophages", "Fibroblasts",
                  "Endothelial cells", "Cholangiocytes", "Hepatocytes")
es[, ct_disp := factor(ct_disp, levels = intersect(stack_levels, unique(ct_disp)))]

# ── Plot ─────────────────────────────────────────────────────────────────────
p <- ggplot(es, aes(x = trans_lab, y = frac, fill = ct_disp)) +
  geom_col(width = 0.74, colour = "white", linewidth = 0.25) +
  scale_fill_manual(values = ct_col, name = NULL,
                    breaks = c("Hepatocytes", "Cholangiocytes", "Endothelial cells",
                               "Fibroblasts", "Macrophages", "T cells")) +
  scale_y_continuous(labels = percent_format(accuracy = 1),
                     expand = expansion(c(0, 0.03))) +
  annotate("text", x = 4, y = 1.03, label = "† n=58", size = 6 / ggplot2::.pt,
           colour = "gray45", vjust = 0) +
  labs(x = "Fibrosis stage (Kleiner F0–F4)",
       y = "Share of intrinsically-carried stage-DEGs") +
  theme_masld_compact() +
  theme(legend.position = "right", legend.key.size = unit(0.28, "cm"))

message("CAPTION Fig S3 (carrier routing): Stage-DEG carrier routing across the fibrosis cascade ",
        "(documented Kleiner F-stage; Andrews n=58 — real recorded F-stage, not ",
        "scVI-inferred). Each bar is one CRN transition; height = the share of that ",
        "transition's bulk stage-DEGs intrinsically carried by each cell type ",
        "(within-cell-type concordant stage effect, strong+likely). Verdict = ",
        "multi-cellular on all transitions (coarse–fine 3/3 agree). Hepatocytes ",
        "(gray) carry stage-DEGs throughout but the F2→F3 fibrosis inflection is ",
        "dominated by non-parenchymal carriers (endothelial, cholangiocyte, ",
        "fibroblast). † F3→F4 is low-power (n=58 documented donors).")

out_pdf <- file.path(PANEL_DIR, "figs3_stagedeg_carrier_routing.pdf")
save_fig(p, out_pdf, width = fig_half_width, height = 2.9)
cat("[fig3D] Saved:", out_pdf, "\n")

# ── Sidecar + sanity print ───────────────────────────────────────────────────
out_csv <- file.path(DATA_DIR, "stagedeg_carrier_routing.csv")
fwrite(es[order(trans_lab, -frac),
          .(transition = trans_lab, cell_type = ct_disp, n_intrinsic,
            frac = round(frac, 4))], out_csv)
cat("[fig3D] Sidecar:", out_csv, "\n")
print(dcast(es, ct_disp ~ trans_lab, value.var = "frac",
            fun.aggregate = function(x) round(100 * x, 1)))
