#!/usr/bin/env python3
"""Shared helpers for the AD.1 gate and the zero-shot local caQTL endpoint.

AD.1 asks whether the LOCAL `google/alphagenome-all-folds` weights reproduce the ARCHIVED hosted
AlphaGenome *Atlas* accessibility ranking on the 3,845 matched Currin caQTL peak leads at
Spearman >= 0.9. That means the local score has to be the same quantity the Atlas column is.

The archived column `alphagenome_atac_liver` is built in
`scripts/analysis/alphagenome_program/c1_matched_endogenous.py:load_atlas_chunks()` as the mean of
the RAW `.X` value over the three liver ATAC tracks of the hosted Atlas `ATAC` scorer. In SDK 0.9.0
that scorer is

    RECOMMENDED_VARIANT_SCORERS['ATAC'] = CenterMaskScorer(
        requested_output=ATAC, width=501, aggregation_type=DIFF_LOG2_SUM)

i.e. log2(1 + sum_alt over a 501-bp variant-centred mask) - log2(1 + sum_ref over the same mask),
per track. DNASE is the same scorer at the same width, averaged over its two liver tracks.

So the local side uses the PACKAGED scorer through `model.score_variant`, not the hand-rolled
+/-2 kb mean-|track| readout of `h1_anchor_hsd17b13.py`. That readout answers a different question
(the hosted model API's indel recipe) and would not be comparable with an Atlas column.
The archived `*_quantile` layer is NOT used: the local runtime ships no calibration table, returns a
predicted track rather than a calibrated quantile, and the runtime probe already recorded that Atlas
quantiles must not be pooled with local values. Raw is compared with raw.

Guards this module enforces, from ADAPTATION_ARM_AMENDMENT_01.md:
  - section 3: every score is produced on ONE card, the card is recorded in every row, and a
    mixed-card table is rescored rather than merged.
  - section 4: the packaged one-hot encoder writes a zero vector for any byte that is not A/C/G/T
    and warns about nothing, so every extracted window is alphabet-validated here before it is
    scored, and every rejected window is counted and reported.

Statistics are the C-package recipe: 1-Mb blocks as the resampling unit, bootstrap seed 20260914,
`fast_spearman` / `fisher_macro` / within-fold block resampling copied verbatim in behaviour from
`c2_03_fit_heads.py` so the comparator this arm is paired against is regenerated by this loader
rather than transcribed.
"""

from __future__ import annotations

import hashlib
import json
import os
import pathlib
import time

import numpy as np

PROJ = pathlib.Path("/gpfs/commons/groups/sanjana_lab/Cas13/MASLD_library_design")

CHECKPOINT = (
    PROJ
    / "Analysis/MASLD_Model_Benchmark/executions/alphagenome-weights-20260915T103442Z/checkpoints"
)
FASTA_PATH = (
    "/gpfs/commons/home/jameslee/reference_genome/cellranger-atac/"
    "refdata-cellranger-arc-GRCh38-2024-A/fasta/genome.fa"
)

# Inputs (all read-only from this arm's point of view).
C1E2 = PROJ / "GWAS/finemapping/results/alphagenome_program/c1-endpoint2-v2-20260915T084559Z"
TIER_A4 = C1E2 / "tables/endpoint1_matched_tierA4.tsv.gz"
C2 = PROJ / "GWAS/finemapping/results/alphagenome_program/c2-endogenous-head-20260914T194000Z"
C2_LABELS = C2 / "inputs/currin_lead_labels.tsv.gz"
C2_OOF = C2 / "tables/oof_predictions.tsv.gz"
C2_METRICS = C2 / "metrics.json"

# The archived Atlas track sets, identical to c1_matched_endogenous.py lines 46-47.
AG_ATAC_TRACKS = ["UBERON:0001114 ATAC-seq", "UBERON:0001115 ATAC-seq", "UBERON:0002107 ATAC-seq"]
AG_DNASE_TRACKS = ["UBERON:0001114 DNase-seq", "UBERON:0001115 DNase-seq"]

# The recipe's pinned liver ontology, unchanged from h1_runtime_common.py. Restricting the returned
# tracks does not change any value: `create_track_masks` selects output columns and the trunk runs
# identically, so this only avoids upcasting the 167 ATAC and 384 DNase columns the archive's own
# loader then threw away.
LIVER_TERMS = ["UBERON:0002107", "UBERON:0001114", "UBERON:0001115", "CL:0000182"]
CENTER_MASK_WIDTH = 501

# Seeds, fixed by IMPLEMENTATION_SPEC.md section 5 and restated in ADAPTATION_ARM_PRESPEC.md.
BOOTSTRAP_SEED = 20260914
COMPARISON_SEEDS = (1103, 2909, 4721, 6673, 8111)
RESAMPLES = 10_000

ACGT = frozenset("ACGT")


def log(msg: str) -> None:
    print(f"[{time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}] {msg}", flush=True)


def sha256_file(path: str | os.PathLike[str], max_bytes: int = 8_000_000_000) -> str:
    if os.path.getsize(path) > max_bytes:
        return "not_hashed_too_large"
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 22), b""):
            h.update(chunk)
    return h.hexdigest()


class ContractError(RuntimeError):
    pass


def write_json(path, obj) -> None:
    path = pathlib.Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as fh:
        json.dump(obj, fh, indent=1, default=_default, sort_keys=True)
    log(f"wrote {path}")


def _default(o):
    if isinstance(o, (np.floating, np.integer)):
        return o.item()
    if isinstance(o, np.bool_):
        return bool(o)
    if isinstance(o, np.ndarray):
        return o.tolist()
    return str(o)


def key_of(chrom, pos, ref, alt) -> str:
    """The join key used across the C packages: chr without the 'chr' prefix."""
    return f"{str(chrom).replace('chr', '')}:{int(pos)}:{str(ref).upper()}:{str(alt).upper()}"


# ------------------------------------------------------------------------------------------------
# model
# ------------------------------------------------------------------------------------------------
def load_model(checkpoint_path=CHECKPOINT, fasta_path: str | None = FASTA_PATH):
    """Restore the local checkpoint onto the first GPU.

    Same construction as `h1_runtime_common.load_model`: the packaged
    `default_organism_settings()` points fasta/gtf/splice/calibration at remote Google Storage URLs,
    which are replaced with the project's own audited GRCh38 FASTA and with None for everything
    else, so nothing is fetched at load time. Metadata is left at the packaged default for BOTH
    organisms, which keeps Orbax's strict checkpoint validation on.

    Consequence recorded here rather than discovered later: with `calibration_path=None` the model
    has no calibration scorer, so `score_variant` returns raw scores and no `quantiles` layer. The
    comparison against the archive is therefore raw-against-raw by construction.
    """
    import dataclasses

    import jax
    from alphagenome.models import dna_model as dna_model_api
    from alphagenome_research.model import dna_model

    settings = dict(dna_model.default_organism_settings())
    human = dna_model_api.Organism.HOMO_SAPIENS
    mouse = dna_model_api.Organism.MUS_MUSCULUS
    settings[human] = dataclasses.replace(
        settings[human],
        fasta_path=fasta_path,
        gtf_feather_path=None,
        pas_feather_path=None,
        splice_site_starts_feather_path=None,
        splice_site_ends_feather_path=None,
        calibration_path=None,
    )
    settings[mouse] = dataclasses.replace(
        settings[mouse],
        fasta_path=None,
        gtf_feather_path=None,
        pas_feather_path=None,
        splice_site_starts_feather_path=None,
        splice_site_ends_feather_path=None,
        calibration_path=None,
    )

    device = jax.local_devices()[0]
    if device.platform != "gpu":
        raise ContractError(f"expected a GPU device, jax offers {jax.local_devices()}")
    t0 = time.time()
    model = dna_model.create(str(checkpoint_path), organism_settings=settings, device=device)
    load_s = time.time() - t0
    log(f"checkpoint restored in {load_s:.1f}s onto {device}")
    return model, device, load_s


def gpu_card() -> dict:
    """The card this process is bound to, recorded in every output row (amendment 01 section 3)."""
    import subprocess

    try:
        out = subprocess.run(
            [
                "nvidia-smi",
                "--query-gpu=name,memory.total,driver_version,compute_cap",
                "--format=csv,noheader",
            ],
            capture_output=True,
            text=True,
            timeout=60,
            check=True,
        ).stdout.strip().splitlines()[0]
    except Exception as exc:  # pragma: no cover - platform dependent
        return {"card": "unknown", "error": repr(exc)}
    name, mem, driver, cap = (p.strip() for p in out.split(","))
    tag = "l40s" if "L40S" in name.upper() else ("b6k" if "BLACKWELL" in name.upper() else "other")
    return {
        "card": name,
        "card_tag": tag,
        "card_memory_total": mem,
        "driver_version": driver,
        "compute_capability": cap,
    }


def memory_stats(device) -> dict:
    try:
        st = device.memory_stats() or {}
    except Exception as exc:  # pragma: no cover
        return {"error": repr(exc)}
    return {k: int(v) for k, v in st.items() if isinstance(v, (int, float))}


def atac_dnase_scorers():
    """The two archived Atlas scorers, taken from the SDK's own recommended dict, not re-specified.

    Returned for their settings only. Their width and aggregation are asserted here so that a later
    SDK that changed either would stop this arm rather than quietly redefine the gate's quantity.
    """
    from alphagenome.models import variant_scorers

    atac = variant_scorers.RECOMMENDED_VARIANT_SCORERS["ATAC"]
    dnase = variant_scorers.RECOMMENDED_VARIANT_SCORERS["DNASE"]
    for s, want in ((atac, "ATAC"), (dnase, "DNASE")):
        if int(s.width) != CENTER_MASK_WIDTH:
            raise ContractError(f"{want} scorer width is {s.width}, expected {CENTER_MASK_WIDTH}")
        if s.aggregation_type.name != "DIFF_LOG2_SUM":
            raise ContractError(f"{want} aggregation is {s.aggregation_type}, expected DIFF_LOG2_SUM")
    return atac, dnase


def center_mask_and_aggregation():
    """The packaged centre-mask builder and aggregation, imported rather than re-implemented.

    `model.score_variant` cannot be used in this offline setup: `_predict_variant` unconditionally
    calls `jnp.asarray(splice_junction_masks.splice_sites)`, and `splice_sites` is None whenever the
    model is built without a splice-site extractor, which is how it is built here because the
    packaged extractor's feather files live behind a Google Storage URL and compute nodes have no
    egress. Requesting a splice annotation in order to score an ATAC track would also change which
    annotation vintage enters the run.

    So the two `predict_sequence` calls the runtime probe already validated are used instead, and the
    Atlas readout is applied with the SAME functions `score_variant` would have applied:
    `create_center_mask` for the mask and `_apply_aggregation` for DIFF_LOG2_SUM. For a matched-
    reference SNV the two routes see identical inputs: `extract_variant_sequences` inserts
    `variant.reference_bases` into the reference window, which is a no-op when the genome base already
    equals REF (checked for every variant), and it inserts the single ALT base for the alternate;
    indel stitching does not apply to a substitution, splice-junction post-processing touches only
    the SPLICE_JUNCTIONS head, and the interval is on the positive strand so strand handling is a
    no-op. What differs is only which track columns are returned, which does not change a value.
    """
    from alphagenome.models import variant_scorers
    from alphagenome_research.model.variant_scoring import center_mask as cm
    from alphagenome_research.model.variant_scoring import variant_scoring as vs

    return cm.create_center_mask, cm._apply_aggregation, variant_scorers.AggregationType, vs.get_resolution


# ------------------------------------------------------------------------------------------------
# window construction and alphabet validation
# ------------------------------------------------------------------------------------------------
def window_bounds(pos1: int, length: int) -> tuple[int, int]:
    """Variant-centred window. The variant's 0-based offset is exactly length // 2."""
    start0 = pos1 - 1 - length // 2
    return start0, start0 + length


def extract_ref_alt(fasta, chrom: str, start0: int, end: int, pos1: int, ref: str, alt: str):
    """The REF and ALT windows for a substitution, uppercased, same length.

    Equivalent to `alphagenome_research.io.genome.extract_variant_sequences` for a same-length
    substitution: the extended_length term is zero, `insert_reference_variant` writes REF over a base
    that already equals REF, and `insert_alternate_variant` writes ALT in its place. The SDK's own
    extractor opens the FASTA with `sequence_always_upper=True`, so uppercasing here matches it.
    """
    width = end - start0
    seq = fasta.fetch(chrom, start0, end).upper()
    if len(seq) != width:
        raise ContractError(f"fasta returned {len(seq)} bp for {chrom}:{start0}-{end}, wanted {width}")
    i = pos1 - 1 - start0
    if seq[i : i + len(ref)] != ref.upper():
        raise ContractError(
            f"reference mismatch at {chrom}:{pos1}: window has {seq[i:i+len(ref)]}, label says {ref}"
        )
    alt_seq = seq[:i] + alt.upper() + seq[i + len(ref) :]
    if len(alt_seq) != width:
        raise ContractError(f"alt window is {len(alt_seq)} bp, wanted {width}")
    if sum(1 for a, b in zip(seq, alt_seq) if a != b) != 1:
        raise ContractError(f"ref and alt windows differ at more than one position at {chrom}:{pos1}")
    return seq, alt_seq


def validate_window(fasta, chrom: str, start0: int, end: int, pos1: int, ref: str) -> dict:
    """Reject any window the packaged encoder would silently zero-vector.

    `alphagenome.io.fasta.FastaExtractor` opens the FASTA with `sequence_always_upper=True`, so
    soft-masked repeats are not the hazard; two other things are. It pads an out-of-bounds interval
    with literal 'N', and a real assembly gap inside the window is 'N' in the FASTA itself. Both
    become zero vectors with no warning, so both are checked here on the same interval the model
    will extract, and a window that fails is not scored and not silently replaced.
    """
    chrom_len = fasta.get_reference_length(chrom)
    rec = {
        "window_start0": start0,
        "window_end": end,
        "chrom_length": chrom_len,
        "out_of_bounds": bool(start0 < 0 or end > chrom_len),
    }
    lo, hi = max(0, start0), min(chrom_len, end)
    seq = fasta.fetch(chrom, lo, hi).upper()
    bad = {}
    for ch in set(seq):
        if ch not in ACGT:
            bad[ch] = seq.count(ch)
    rec["n_non_acgt"] = int(sum(bad.values())) + (end - start0) - len(seq)
    rec["non_acgt_characters"] = bad
    observed = seq[pos1 - 1 - lo] if lo <= pos1 - 1 < hi else ""
    rec["reference_base"] = observed
    rec["reference_match"] = bool(observed == str(ref).upper()[0])
    rec["acgt_ok"] = bool(rec["n_non_acgt"] == 0 and not rec["out_of_bounds"])
    return rec


# ------------------------------------------------------------------------------------------------
# statistics, behaviour copied from c2_03_fit_heads.py so the comparator is regenerated not quoted
# ------------------------------------------------------------------------------------------------
def fast_spearman(observed: np.ndarray, predicted: np.ndarray) -> float:
    from scipy.stats import rankdata

    observed = np.asarray(observed, dtype=np.float64)
    predicted = np.asarray(predicted, dtype=np.float64)
    if observed.size < 3 or np.all(predicted == predicted[0]) or np.all(observed == observed[0]):
        return float("nan")
    left = rankdata(observed)
    right = rankdata(predicted)
    left = left - left.mean()
    right = right - right.mean()
    denominator = float(np.sqrt(np.sum(left**2) * np.sum(right**2)))
    return float("nan") if denominator == 0 else float(np.sum(left * right) / denominator)


def fisher_macro(values) -> float:
    array = np.asarray(values, dtype=np.float64)
    if not np.isfinite(array).all():
        return float("nan")
    clipped = np.clip(array, -0.999999, 0.999999)
    return float(np.tanh(np.mean(np.arctanh(clipped))))


def macro_over_folds(observed: np.ndarray, predicted: np.ndarray, folds: np.ndarray, n_folds=5) -> float:
    return fisher_macro(
        [fast_spearman(observed[folds == f], predicted[folds == f]) for f in range(n_folds)]
    )


def interval_of(samples: np.ndarray) -> tuple[float, float, float]:
    valid = samples[np.isfinite(samples)]
    if valid.size < int(0.95 * samples.size):
        return float("nan"), float("nan"), float("nan")
    low, high = (float(v) for v in np.quantile(valid, (0.025, 0.975)))
    return low, high, float(np.std(valid, ddof=1))


def bootstrap_p(diff_samples: np.ndarray) -> tuple[float, str]:
    d = diff_samples[np.isfinite(diff_samples)]
    if d.size == 0:
        return float("nan"), "no_valid_draws"
    p = 2.0 * min(float((d <= 0).mean()), float((d >= 0).mean()))
    p = min(1.0, p)
    floor = 1.0 / d.size
    if p < floor:
        return floor, f"floored_at_1/{d.size}_draws"
    return float(p), ""


def block_bootstrap_plain(
    observed: np.ndarray,
    arms: dict,
    blocks: np.ndarray,
    *,
    resamples: int = RESAMPLES,
    seed: int = BOOTSTRAP_SEED,
) -> dict:
    """Resample 1-Mb blocks with replacement; every arm recomputed inside the SAME draw.

    Used for the AD.1 gate correlation, which has no fold structure: the gate compares two score
    sets to each other, and the resampling unit is still the 1-Mb block.
    """
    unique = np.array(sorted(set(blocks.tolist())))
    lookup = {b: np.flatnonzero(blocks == b) for b in unique}
    rng = np.random.default_rng(seed)
    out = {name: np.full(resamples, np.nan) for name in arms}
    for it in range(resamples):
        sampled = rng.integers(0, unique.size, size=unique.size)
        idx = np.concatenate([lookup[unique[j]] for j in sampled])
        obs = observed[idx]
        for name, values in arms.items():
            out[name][it] = fast_spearman(obs, values[idx])
    return out


def block_bootstrap_within_fold(
    observed: np.ndarray,
    arms: dict,
    folds: np.ndarray,
    blocks: np.ndarray,
    *,
    resamples: int = RESAMPLES,
    seed: int = BOOTSTRAP_SEED,
    n_folds: int = 5,
) -> tuple[dict, dict]:
    """Identical in behaviour to `c2_03_fit_heads.block_bootstrap`.

    Blocks are resampled WITHIN each held-out fold, every arm is recomputed inside the same draw
    (so arm differences are paired), the macro is the Fisher-z average over folds and the pooled
    statistic is the single Spearman over the concatenated draw.
    """
    by_fold = {}
    empty = []
    for fold in range(n_folds):
        rows = np.flatnonzero(folds == fold)
        unique = sorted(set(blocks[rows].tolist()))
        if not unique:
            empty.append(fold)
        by_fold[fold] = (unique, {b: rows[blocks[rows] == b] for b in unique})
    if empty:
        # A Fisher-z macro over folds is undefined if a fold contributes nothing, and resampling an
        # empty fold fails inside numpy with an error that names neither the fold nor the cause.
        raise ContractError(
            f"held-out fold(s) {empty} carry no variants, so a 5-fold macro cannot be formed; "
            f"fold sizes are {[int((folds == f).sum()) for f in range(n_folds)]}"
        )
    rng = np.random.default_rng(seed)
    macro = {name: np.full(resamples, np.nan) for name in arms}
    pooled = {name: np.full(resamples, np.nan) for name in arms}
    names = list(arms)
    for it in range(resamples):
        per_fold = []
        for fold in range(n_folds):
            unique, lookup = by_fold[fold]
            sampled = rng.integers(0, len(unique), size=len(unique))
            per_fold.append(np.concatenate([lookup[unique[j]] for j in sampled]))
        all_idx = np.concatenate(per_fold)
        fold_obs = [observed[i] for i in per_fold]
        pooled_obs = observed[all_idx]
        for name in names:
            v = arms[name]
            macro[name][it] = fisher_macro(
                [fast_spearman(fold_obs[f], v[per_fold[f]]) for f in range(n_folds)]
            )
            pooled[name][it] = fast_spearman(pooled_obs, v[all_idx])
    return macro, pooled
