channels:
  - conda-forge
  - bioconda
channel_priority: strict
dependencies:
  - r-base=4.6
  - r-biocmanager
  - r-data.table
  - r-digest
  - r-matrix
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-biocversion=3.23
  - bioconductor-chromvar
  - bioconductor-genomicranges
  - bioconductor-jaspar2024
  - bioconductor-limma
  - bioconductor-motifmatchr
  - bioconductor-summarizedexperiment
  - bioconductor-tfbstools
