#!/usr/bin/env Rscript
# 340_scploidy_hepatocyte.R
# scPloidy on scATAC hepatocyte fragments per donor.
# Inputs:  fragments/<donor>_fragments.tsv.gz, hepatocyte barcode TSV
# Outputs: scploidy_percell_<donor>.csv.gz, scploidy_donor_summary.csv (aggregated by run_aggregate),
#          scploidy_model_fits_<donor>.rds, qc/<donor>_diagnostic.pdf
#
# Run per-donor (DONOR_ID env var) or all donors sequentially if unset.
# Method: Takeuchi & Kato 2024 Genetics (DOI 10.1093/genetics/iyae061)

suppressPackageStartupMessages({
  library(scPloidy)
  library(GenomicRanges)
  library(IRanges)
  library(data.table)
  library(readr)
})

# hg38 autosome lengths (GRCh38 primary assembly, chr1-22). Hardcoded to avoid the
# BSgenome.Hsapiens.UCSC.hg38 dependency (not installed in `scploidy` env).
HG38_AUTO_LEN <- c(
  chr1=248956422,  chr2=242193529,  chr3=198295559,  chr4=190214555,
  chr5=181538259,  chr6=170805979,  chr7=159345973,  chr8=145138636,
  chr9=138394717,  chr10=133797422, chr11=135086622, chr12=133275309,
  chr13=114364328, chr14=107043718, chr15=101991189, chr16=90338345,
  chr17=83257441,  chr18=80373285,  chr19=58617616,  chr20=64444167,
  chr21=46709983,  chr22=50818468
)

PROJECT_ROOT <- Sys.getenv("MASLD_PROJECT_ROOT",
                           "/gpfs/commons/groups/sanjana_lab/Cas13/MASLD_library_design")
setwd(PROJECT_ROOT)

FRAG_DIR       <- "Analysis/ATAC/Human_Multiome/results/fragments"
BARCODE_TSV    <- "Analysis/SingleCell/results_gpu_v2/ploidy/hepatocyte_barcodes.tsv.gz"
SIMPLE_REPEAT  <- "data/ucsc_hg38/simpleRepeat.hg38.txt.gz"  # downloaded below if missing
OUT_DIR        <- "Analysis/SingleCell/results_gpu_v2/ploidy"
SCRATCH_DIR    <- file.path("/scratch", Sys.getenv("USER", "claude"), "scploidy_filter")
dir.create(OUT_DIR, recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(OUT_DIR, "qc"), showWarnings = FALSE)
dir.create(SCRATCH_DIR, recursive = TRUE, showWarnings = FALSE)

DONOR_ARG <- Sys.getenv("DONOR_ID", "")
PLOIDY_LEVELS <- c(2, 4, 8)
TN5_OFFSET    <- c(1, 0)   # 10x Cell Ranger format (vignette: "Using fragments.tsv.gz generated by 10x Cell Ranger")
MIN_HEP_CELLS <- 100       # below this, the EM is unreliable; we log a warning but still try

# ---- Step 1: hg38 autosome target regions (from hardcoded lengths) ----
autosomes <- names(HG38_AUTO_LEN)
target_regions <- GRanges(
  seqnames = autosomes,
  ranges   = IRanges(start = 1L, end = HG38_AUTO_LEN)
)

# ---- Step 2: simpleRepeat exclusion (download if missing) ----
if (!file.exists(SIMPLE_REPEAT)) {
  dir.create(dirname(SIMPLE_REPEAT), recursive = TRUE, showWarnings = FALSE)
  url <- "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/simpleRepeat.txt.gz"
  cat("[", format(Sys.time()), "] Downloading simpleRepeat.txt.gz from UCSC...\n", sep = "")
  download.file(url, SIMPLE_REPEAT, mode = "wb")
}
cat("[", format(Sys.time()), "] Loading simpleRepeat...\n", sep = "")
# UCSC simpleRepeat columns: bin chrom chromStart chromEnd name period copyNum ... (17 cols total)
sr <- fread(
  cmd = paste("zcat", shQuote(SIMPLE_REPEAT)),
  header = FALSE, sep = "\t", select = c(2, 3, 4),
  col.names = c("chrom", "chromStart", "chromEnd")
)
sr[, chromStart := chromStart + 1L]   # UCSC half-open -> 1-based closed
sr <- sr[chrom %in% autosomes]
simpleRepeat <- GenomicRanges::makeGRangesFromDataFrame(
  sr, seqnames.field = "chrom", start.field = "chromStart", end.field = "chromEnd"
)
cat("  simpleRepeat regions:", length(simpleRepeat), "\n")

# ---- Step 3: hepatocyte barcode table ----
bc <- fread(BARCODE_TSV)
stopifnot(all(c("barcode", "donor_id", "condition") %in% names(bc)))

donor_list <- if (nzchar(DONOR_ARG)) DONOR_ARG else sort(unique(bc$donor_id))
cat("[", format(Sys.time()), "] Donors to process:", paste(donor_list, collapse = ","), "\n", sep = "")

# ---- Step 4: per-donor scPloidy ----
run_one_donor <- function(donor) {
  cat("\n=== Donor", donor, "===\n")
  bc_d <- bc[donor_id == donor, barcode]
  if (length(bc_d) < MIN_HEP_CELLS) {
    cat("  [WARN] only", length(bc_d), "hepatocyte cells (<", MIN_HEP_CELLS, ") for", donor,
        "- recording and skipping fit\n")
    return(data.frame(
      donor_id = donor, status = "skipped_too_few_cells",
      n_hepatocyte = length(bc_d),
      stringsAsFactors = FALSE
    ))
  }

  frag_in  <- file.path(FRAG_DIR, paste0(donor, "_fragments.tsv.gz"))
  if (!file.exists(frag_in)) {
    cat("  [ERROR] missing fragments file:", frag_in, "\n")
    return(data.frame(donor_id = donor, status = "missing_fragments", stringsAsFactors = FALSE))
  }

  # Fragment overlap counts per cell - pass hepatocyte barcodes directly via targetbarcodes
  cat("[", format(Sys.time()), "] fragmentoverlapcount() on", length(bc_d),
      "hepatocyte barcodes ...\n", sep = "")
  t0 <- Sys.time()
  fo <- tryCatch(
    fragmentoverlapcount(
      file           = frag_in,
      targetregions  = target_regions,
      excluderegions = simpleRepeat,
      targetbarcodes = bc_d,
      Tn5offset      = TN5_OFFSET
    ),
    error = function(e) {
      cat("  [ERROR fragmentoverlapcount]", conditionMessage(e), "\n"); NULL
    }
  )
  if (is.null(fo)) return(data.frame(donor_id = donor, status = "fail_fragmentoverlap", stringsAsFactors = FALSE))
  cat("  fragmentoverlapcount: ", round(difftime(Sys.time(), t0, units = "mins"), 1), " min, ",
      nrow(fo), " barcodes returned\n", sep = "")

  # Ploidy inference (mixture EM at 2N/4N/8N; recommended method is moment)
  cat("[", format(Sys.time()), "] ploidy() ...\n", sep = "")
  t0 <- Sys.time()
  pl <- tryCatch(
    ploidy(fo, PLOIDY_LEVELS),
    error = function(e) { cat("  [ERROR ploidy]", conditionMessage(e), "\n"); NULL }
  )
  if (is.null(pl)) return(data.frame(donor_id = donor, status = "fail_ploidy_em", stringsAsFactors = FALSE))
  cat("  ploidy: ", round(difftime(Sys.time(), t0, units = "secs"), 1), " sec\n", sep = "")

  # Annotate per cell with donor + condition
  cond <- unique(bc[donor_id == donor, condition])[1]
  pl$donor_id  <- donor
  pl$condition <- cond

  # Save per-donor outputs
  out_csv <- file.path(OUT_DIR, paste0("scploidy_percell_", donor, ".csv.gz"))
  fwrite(pl, out_csv, compress = "gzip")
  cat("  wrote", out_csv, "(", nrow(pl), "cells)\n")
  out_rds <- file.path(OUT_DIR, paste0("scploidy_model_fits_", donor, ".rds"))
  saveRDS(list(fragmentoverlap = fo, ploidy = pl, donor = donor, condition = cond,
               target_regions = target_regions, n_simpleRepeat = length(simpleRepeat)),
          out_rds)
  cat("  wrote", out_rds, "\n")

  # Per-donor summary stats
  # NB: With our 10x multiome coverage (~1.6k fragments/cell) the discrete moment calls
  # are biased toward higher ploidy vs the rat scATAC dataset scPloidy was validated on
  # (~28k fragments/cell). We report BOTH the discrete calls (for completeness) AND the
  # continuous `ploidy.momentfractional` as the primary metric for relative comparisons.
  pcol <- if ("ploidy.moment" %in% names(pl)) "ploidy.moment" else
          if ("ploidy" %in% names(pl)) "ploidy" else names(pl)[grepl("^ploidy", names(pl))][1]
  tab <- table(factor(pl[[pcol]], levels = PLOIDY_LEVELS))
  # Cell-level fragment counts for coverage diagnostics
  fo_dt <- as.data.frame(fo)
  med_nfrags <- median(fo_dt$nfrags, na.rm = TRUE)
  pl_dt <- as.data.frame(pl)
  frac_med <- median(pl_dt$ploidy.momentfractional, na.rm = TRUE)
  frac_mean <- mean(pl_dt$ploidy.momentfractional, na.rm = TRUE)
  # Depth-filtered sensitivity: cells with nfrags > 5000 (closer to rat-demo regime)
  hi_bc <- fo_dt$barcode[fo_dt$nfrags > 5000]
  pl_hi <- pl_dt[pl_dt$barcode %in% hi_bc, , drop = FALSE]
  tab_hi <- table(factor(pl_hi[[pcol]], levels = PLOIDY_LEVELS))
  summary_row <- data.frame(
    donor_id     = donor,
    condition    = cond,
    n_hepatocyte = length(bc_d),
    n_cells_fit  = nrow(pl),
    median_nfrags = med_nfrags,
    n_2N         = as.integer(tab["2"]),
    n_4N         = as.integer(tab["4"]),
    n_8N         = as.integer(tab["8"]),
    frac_2N      = as.numeric(tab["2"]) / sum(tab),
    frac_4N      = as.numeric(tab["4"]) / sum(tab),
    frac_8N      = as.numeric(tab["8"]) / sum(tab),
    polyploid_frac = (as.numeric(tab["4"]) + as.numeric(tab["8"])) / sum(tab),
    mean_fractional_ploidy = frac_mean,
    median_fractional_ploidy = frac_med,
    # Depth-filtered (nfrags > 5000) version
    n_cells_hi_depth   = sum(fo_dt$nfrags > 5000),
    frac_2N_hi_depth   = as.numeric(tab_hi["2"]) / max(sum(tab_hi), 1),
    frac_4N_hi_depth   = as.numeric(tab_hi["4"]) / max(sum(tab_hi), 1),
    frac_8N_hi_depth   = as.numeric(tab_hi["8"]) / max(sum(tab_hi), 1),
    polyploid_frac_hi_depth = (as.numeric(tab_hi["4"]) + as.numeric(tab_hi["8"])) /
                              max(sum(tab_hi), 1),
    method_col   = pcol,
    status       = "ok",
    stringsAsFactors = FALSE
  )
  cat("  Summary:", paste(names(summary_row),
        round(unlist(summary_row[sapply(summary_row, is.numeric)]), 3),
        sep = "=", collapse = "  "), "\n")

  # Quick diagnostic PDF (per-cell ploidy histogram + nfrags distribution)
  pdf(file.path(OUT_DIR, "qc", paste0(donor, "_diagnostic.pdf")), width = 10, height = 4)
  par(mfrow = c(1, 3))
  hist(log10(fo_dt$nfrags + 1), breaks = 60,
       main = paste(donor, "log10(nfrags+1) per cell"),
       xlab = "log10(nfrags+1)")
  abline(v = log10(5001), col = "red", lty = 2)
  barplot(prop.table(tab),
          main = paste(donor, cond, "ploidy proportions"),
          names.arg = paste0(names(tab), "N"),
          ylab = "fraction", ylim = c(0, 1), col = c("#4d9221", "#e7298a", "#7570b3"))
  hist(pl_dt$ploidy.momentfractional, breaks = 60,
       main = paste(donor, "fractional ploidy"),
       xlab = "ploidy.momentfractional")
  abline(v = c(2, 4, 8), col = "blue", lty = 2)
  dev.off()

  return(summary_row)
}

# Execute
results <- lapply(donor_list, run_one_donor)
# Pad rows to a unified column set (some donors fail before all stats are computed)
all_cols <- unique(unlist(lapply(results, names)))
results <- do.call(rbind, lapply(results, function(x) {
  for (c in all_cols) if (!c %in% names(x)) x[[c]] <- NA
  as.data.frame(x[all_cols], stringsAsFactors = FALSE)
}))

# Append (don't overwrite) to allow per-donor sbatch array
sum_path <- file.path(OUT_DIR, "scploidy_donor_summary.csv")
if (file.exists(sum_path) && nzchar(DONOR_ARG)) {
  prev <- fread(sum_path)
  prev <- prev[!(donor_id %in% results$donor_id)]
  results <- rbind(prev, results, fill = TRUE)
}
fwrite(results, sum_path)
cat("\n[", format(Sys.time()), "] DONE. Summary:\n", sep = "")
print(results)
