#!/usr/bin/env Rscript
# Mouse scRNA-seq Pseudobulk DE Analysis
#
# Runs limma-voom on pseudobulk counts generated by mouse_pseudobulk_de.py.
#
# Contrast: ALIOS vs Normal_Chow (GSE189600; 2 samples per group)
# Note: n=2 per group is very low; results are exploratory/directional only.
#       The species_effect_size_norm.R script will supplement with bulk mouse DE.
#
# Input:  results_gpu_v2/mouse_sc/pseudobulk/{celltype}_pseudobulk.csv
#         results_gpu_v2/mouse_sc/sample_metadata.csv
# Output: results_gpu_v2/mouse_sc/{celltype}_de.csv

suppressPackageStartupMessages({
  library(limma)
  library(edgeR)
  library(data.table)
})

BASE <- Sys.getenv("MASLD_PROJECT_ROOT",
                   "/gpfs/commons/groups/sanjana_lab/Cas13/MASLD_library_design")

mouse_sc_dir <- file.path(BASE, "Analysis/SingleCell/results_gpu_v2/mouse_sc")
pb_dir       <- file.path(mouse_sc_dir, "pseudobulk")
out_dir      <- mouse_sc_dir
meta_path    <- file.path(mouse_sc_dir, "sample_metadata.csv")

# ---------------------------------------------------------------------------
# 1. Load sample metadata
# ---------------------------------------------------------------------------
if (!file.exists(meta_path)) {
  stop("Sample metadata not found: ", meta_path,
       "\nRun mouse_pseudobulk_de.py first.")
}

meta <- fread(meta_path)
message("Sample metadata: ", nrow(meta), " samples")
message("  Conditions: ", paste(names(table(meta$condition)),
                                 table(meta$condition), sep = "=", collapse = ", "))

# Filter to GSE189600 (ALIOS vs Normal_Chow) for the binary DE
# Note: n=2 per group — results are directional/exploratory only
de_meta <- meta[dataset == "GSE189600" & condition %in% c("ALIOS", "Normal_Chow")]
message("  DE-eligible samples (GSE189600, ALIOS/Normal_Chow): ", nrow(de_meta))

if (nrow(de_meta) < 4) {
  message("WARNING: Very few samples (n=", nrow(de_meta), "). ",
          "Results will be exploratory only.")
}

if (nrow(de_meta) == 0) {
  stop("No DE-eligible samples found.")
}

# ---------------------------------------------------------------------------
# 2. Run limma-voom per cell type
# ---------------------------------------------------------------------------
pb_files <- list.files(pb_dir, pattern = "_pseudobulk\\.csv$", full.names = TRUE)
message("\nFound ", length(pb_files), " pseudobulk files")

for (pb_file in pb_files) {
  ct_name <- sub("_pseudobulk\\.csv$", "", basename(pb_file))
  message("\n--- ", ct_name, " ---")

  # Load count matrix (genes x all samples)
  counts_dt <- fread(pb_file)
  gene_col  <- colnames(counts_dt)[1]  # first col is gene name
  gene_names <- counts_dt[[gene_col]]
  counts_mat <- as.matrix(counts_dt[, -1, with = FALSE])
  rownames(counts_mat) <- gene_names

  # Subset to DE-eligible samples
  de_samples <- de_meta$sample
  avail <- intersect(de_samples, colnames(counts_mat))
  if (length(avail) < 3) {
    message("  Skipping: only ", length(avail), " DE-eligible samples present")
    next
  }

  counts_mat <- counts_mat[, avail, drop = FALSE]
  matched <- de_meta[sample %in% avail]

  cond_tab <- table(matched$condition)
  if (any(cond_tab < 2)) {
    message("  Skipping: need >=2 samples per condition (",
            paste(names(cond_tab), cond_tab, sep = "=", collapse = ", "), ")")
    next
  }

  # Filter low-expression genes (>=3 counts in >=2 samples; lenient for n=2)
  keep_genes <- rowSums(counts_mat >= 3) >= 2
  counts_mat <- counts_mat[keep_genes, , drop = FALSE]
  message("  Samples: ", ncol(counts_mat),
          " (", paste(names(cond_tab), cond_tab, sep = "=", collapse = ", "), ")")
  message("  Genes after filtering: ", nrow(counts_mat))

  if (nrow(counts_mat) < 50) {
    message("  Skipping: too few genes (", nrow(counts_mat), ")")
    next
  }

  # Design: ALIOS vs Normal_Chow (Normal_Chow as reference → MASLD-like)
  condition <- factor(matched$condition, levels = c("Normal_Chow", "ALIOS"))

  design <- model.matrix(~ condition)
  colnames(design)[ncol(design)] <- "ALIOS_vs_NormalChow"

  tryCatch({
    dge  <- DGEList(counts = counts_mat)
    dge  <- calcNormFactors(dge)
    v    <- voom(dge, design, plot = FALSE)
    fit  <- lmFit(v, design)
    fit  <- eBayes(fit)

    res <- topTable(fit, coef = "ALIOS_vs_NormalChow", number = Inf,
                    sort.by = "none")
    res$gene      <- rownames(res)
    res$cell_type <- ct_name
    res$contrast  <- "ALIOS_vs_NormalChow"
    res$n_samples <- ncol(counts_mat)
    res$note      <- "Exploratory: n=2 per group"

    setnames(setDT(res),
             old = c("adj.P.Val", "P.Value", "t"),
             new = c("padj",      "pvalue",  "t_stat"),
             skip_absent = TRUE)

    out_file <- file.path(out_dir, paste0(ct_name, "_de.csv"))
    fwrite(res, out_file)
    message("  Saved: ", out_file,
            " (", nrow(res), " genes, ",
            sum(res$padj < 0.1, na.rm = TRUE), " at padj<0.1)")
  }, error = function(e) {
    message("  ERROR: ", e$message)
  })
}

message("\n=== Mouse pseudobulk DE complete. Results in: ", out_dir, " ===")
