"""Data path resolution for the MASLD Atlas Streamlit app.

Resolves ``DATA_DIR`` in priority order:

1. Environment variable ``MASLD_DATA_DIR`` (explicit override)
2. ``../masld-atlas-v2/public/data`` relative to this file (local dev beside the
   Next.js site)
3. ``./data_cache`` under the Streamlit app root (HF Space fallback where data
   has been copied in at build time)

Every helper below returns a :class:`pathlib.Path`; callers are responsible for
checking ``.exists()`` (the loaders layer does this and surfaces helpful errors).
"""
from __future__ import annotations

import functools
import os
from pathlib import Path


@functools.lru_cache(maxsize=1)
def data_dir() -> Path:
    """Resolve the directory holding atlas JSON/Parquet files."""
    env = os.environ.get("MASLD_DATA_DIR")
    if env:
        return Path(env).expanduser().resolve()

    # Repo-local sibling: masld-atlas-v2/public/data
    nextjs = Path(__file__).resolve().parent.parent.parent / "masld-atlas-v2" / "public" / "data"
    if nextjs.exists():
        return nextjs

    # HF Space fallback: data copied into the app at build time
    local = Path(__file__).resolve().parent.parent / "data_cache"
    return local


# ---------------------------------------------------------------------------
# Individual path helpers
# ---------------------------------------------------------------------------

def summary_json() -> Path:
    return data_dir() / "atlas_summary.json"


def featured_genes() -> Path:
    return data_dir() / "featured_genes.json"


def gene_index() -> Path:
    return data_dir() / "gene_index.json"


def convergence_matrix() -> Path:
    return data_dir() / "convergence_matrix.json"


def bayesian_ranking() -> Path:
    """Canonical Bayesian ranking (Script 46d, 2026-04-23 onward).

    The legacy 46b archetype-similarity output was retired
    on 2026-04-23 — see archive/46b_retired_2026-04-23/.
    """
    return data_dir() / "bayesian_ranking.json"


def proteomics_summary() -> Path:
    return data_dir() / "proteomics_summary.json"


def atlas_parquet() -> Path:
    """Large wide table for Atlas / Explorer pages.

    Prefer the repo-local Parquet (generated by ``build_parquet.py``) if it
    exists; otherwise fall back to the Next.js served copy.
    """
    local = Path(__file__).resolve().parent.parent / "atlas.parquet"
    if local.exists():
        return local
    return data_dir() / "atlas.parquet"


def gene_profile_path(symbol: str) -> Path:
    return data_dir() / "genes" / f"{symbol}.json"


def gene_graph_path(symbol: str) -> Path:
    """Portal-export v4 per-gene JSON (network/portal_export_v2/gene_graphs/<SYMBOL>.json)."""
    return data_dir() / "network" / "portal_export_v2" / "gene_graphs" / f"{symbol}.json"


def community_labels() -> Path:
    return data_dir() / "network" / "portal_export_v2" / "community_labels.json"


def filter_indexes_dir() -> Path:
    return data_dir() / "network" / "portal_export_v2" / "filter_indexes"


def query_bundles_dir() -> Path:
    return data_dir() / "network" / "portal_export_v2" / "query_bundles"


def cross_species() -> Path:
    return data_dir() / "cross_species.json"


def drug_pipeline() -> Path:
    return data_dir() / "drug_pipeline.json"


def clinical_drugs_csv() -> Path:
    """Fallback source if clinical_drugs.json not present."""
    return (
        Path(__file__).resolve().parent.parent.parent
        / "RNA-seq"
        / "results"
        / "drug_repurposing"
        / "clinical_drug_validation_table.csv"
    )


def knowledge_graph() -> Path:
    return data_dir() / "knowledge_graph.json"
