#!/usr/bin/env python3
"""
src/80_direction_hardened.py — Phase-5 DEFINITIVE HARDENED direction benchmark.

============================================================================
⛔ SUPERSEDED (Phase 6, 2026-07-11) — ToS-NONCOMPLIANT caQTL/eQTL SUPERVISED ARMS.
   The eQTL and caQTL panels TRAIN a LogisticRegression/GBT on AlphaGenome
   output features (ag_gene_lfc, ag_accessibility_delta, ag_dnase_delta,
   ag_splice_score, ag_atac_delta_labelframe). The AlphaGenome FAQ forbids this:
   "Outputs generated by AlphaGenome should not be used for the training of other
   machine learning models" (+ non-commercial use only). These trained arms MUST
   NOT be cited or re-run for any paper claim.
   REPLACEMENTS (ToS-clean, zero-shot, no model trained on any AG feature):
     - caQTL direction  -> src/84_caqtl_zeroshot.py  (per-model zero-shot sign-
                           auROC; headline = best OPEN model Borzoi-ATAC ~0.75
                           signal-level; AG reported only as zero-shot annotation)
     - eQTL direction    -> src/85_eqtl_signal_diagnose.py (signal-level, GOT2-
                           deduped, zero-shot Borzoi logSED + AG-native diagnostic)
   This file is retained for provenance only. Do NOT delete.
============================================================================

Pre-registered, leakage-tiered, apply-only-firewalled supervised-vs-zero-shot
DIRECTION benchmark. Answers ONE scientific question per panel: can a supervised
meta-learner over sequence-model features recover the SIGN of a measured QTL
effect, and does it clear the RIGHT bar (fold-unanimous zero-shot rule, gated
sign, aggregated signed score, AND a MAF+distance positional control)?

This is a BENCHMARK ONLY. It NEVER emits per-locus direction on the
convergence / eQTL-absent set (apply-only firewall). caQTL/sQTL are the SAME
genetic axis — corroboration/labels, never a scored convergence channel.

--------------------------------------------------------------------------- PRE-REGISTRATION (LOCKED)
PRIMARY ENDPOINT (ONE test):
    estimator      = elastic-net logistic (StandardScaler -> saga, nested-LOCO tuned)
    panel          = eQTL Broadaway liver (clean_primary; independent microarray,
                     NOT in Borzoi/AlphaGenome training)
    statistic      = POOLED out-of-fold sign-auROC (leave-one-CHROMOSOME-out)
    GO criterion   = block-bootstrap lower-95% CI(auROC) > 0.56
    AND must beat, with CI-separated margins (lower-95% of the paired
    block-bootstrap difference > 0), ALL of:
        (b1) fold-unanimous zero-shot rule
        (b2) |logSED|-gated sign
        (b3) aggregated signed logSED / signed-feature mean
        (b4) MAF + TSS-distance-only logistic (positional control:
             proves biology, not allele-frequency/position)
SECONDARY (CERTIFIED): caQTL Currin primary-hepatocyte (clean_secondary),
    accessibility features, same protocol. Question the review foregrounds:
    does accessibility-direction (caQTL) beat expression-direction (eQTL)?
EXPLORATORY (NEVER CERTIFIED, hard leakage-flagged): GTEx v8 liver sQTL —
    GTEx IS in Borzoi+AG training. Splice phenotype = leafcutter intron-excision
    ratio; magnitude-dominated. Reported behind an explicit leakage caveat only.
MULTIPLICITY: primary = the single locked endpoint above. All non-primary
    panel x baseline comparisons carry a Bonferroni-adjusted flag.
SIGNIFICANCE: >=1000x LABEL-PERMUTATION null (fixed-hyperparam estimator, matched
    observed statistic), per panel. CI: block bootstrap resampling whole chromosomes.
LEAKAGE-GAP: chromosome-holdout auROC vs random-split auROC per panel (optimism).
ORIENTATION: every signed feature re-expressed in the label REF->ALT frame via an
    explicit orient_mult (fasta/allele swap propagation); strand-ambiguous A/T & C/G
    already hard-dropped upstream (src/78). SORT1 rs12740374 sign unit-check.

ADDITIVE ONLY. Reads direction_labels_*.tsv (src/78) + existing SF feature tables
(eQTL: borzoi_eqtl_logsed_scores/alphagenome_eqtl_scores) + direction_features_*.tsv
(src/79, caQTL/sQTL). Writes direction_hardened_{verdict.json,results.csv} + README.
Does NOT touch 74-77 / 46d / 78 / 27a / 60-73. Env: rnaseq (sklearn 1.6, pandas, numpy).

Author: supervised-direction hardened build (Phase 5).
"""
import argparse
import json
import os
import sys
import time
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")
os.environ.setdefault("PYTHONWARNINGS", "ignore")

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import roc_auc_score

# ----------------------------------------------------------------------------- paths
ROOT = os.environ.get("MASLD_PROJECT_ROOT",
                      "/gpfs/commons/groups/sanjana_lab/Cas13/MASLD_library_design")
SF = os.path.join(ROOT, "GWAS/finemapping/results/seqfunc")
LAB_EQTL = os.path.join(SF, "direction_labels_eqtl.tsv")
BORZOI_EQTL = os.path.join(SF, "borzoi_eqtl_logsed_scores.tsv")
AG_EQTL = os.path.join(SF, "alphagenome_eqtl_scores.tsv")
FEAT_CAQTL = os.path.join(SF, "direction_features_caqtl.tsv")
FEAT_SQTL = os.path.join(SF, "direction_features_sqtl.tsv")

OUT_RESULTS = os.path.join(SF, "direction_hardened_results.csv")
OUT_VERDICT = os.path.join(SF, "direction_hardened_verdict.json")
OUT_README = os.path.join(SF, "direction_hardened.README.md")

# ----------------------------------------------------------------------------- constants
PRIMARY_BAR = 0.56                    # locked GO threshold (lower-95% CI must exceed)
FOLD_UNANIMOUS_REF = 0.649            # prior zero-shot rule (context; recomputed here)
SORT1_CHR, SORT1_POS = "1", 109274968  # rs12740374 G>T; alt T -> up expr/accessibility -> sign +1
COMP = {"A": "T", "T": "A", "C": "G", "G": "C", "N": "N"}

# elastic-net tuning grid (nested inner-LOCO)
ENET_C = [0.03, 0.1, 0.3, 1.0]
ENET_L1 = [0.1, 0.5, 0.9]

RNG = np.random.default_rng(42)


def log(m):
    print(f"[{time.strftime('%H:%M:%S')}] {m}", flush=True)


def nc(c):
    c = str(c)
    return c[3:] if c.lower().startswith("chr") else c


def cp(c, p):
    return f"{nc(c)}:{int(p)}"


def orient_mult(lref, lalt, fref, falt):
    """+1 if feature ref->alt already == label ref->alt; -1 if swapped;
    complement handling for a genome-strand flip. 0/None if irreconcilable.
    Signed feature * orient_mult => label REF->ALT frame."""
    lref, lalt, fref, falt = (str(x).upper() for x in (lref, lalt, fref, falt))
    if (lref, lalt) == (fref, falt):
        return 1
    if (lref, lalt) == (falt, fref):
        return -1
    cf_ref, cf_alt = COMP.get(fref), COMP.get(falt)
    if (lref, lalt) == (cf_ref, cf_alt):
        return 1
    if (lref, lalt) == (cf_alt, cf_ref):
        return -1
    return 0


# ============================================================ eQTL matrix (expression LABEL)
# NOTE (feature provenance, disclosed): the eQTL panel predicts the expression-direction
# LABEL from the FULL signed sequence-effect panel — 4 expression deltas
# (borzoi_logsed_liver, borzoi_logsed_allliver, ag_gene_lfc, ag_gene_lfc_alltracks) PLUS
# 3 accessibility deltas (borzoi_acc_delta, ag_accessibility_delta, ag_dnase_delta) and
# 1 splice delta (ag_splice_score). This is a SUPERSET of the strict expression-only head
# named in the pre-registration (README item 2). It is retained deliberately: extra signed
# predictors can only give the model MORE information, so the at-chance result (0.507) is a
# CONSERVATIVE negative — the model fails to predict expression direction even with the
# accessibility/splice heads added. (A strict 4-expression-feature refit is available as a
# sensitivity arm; it does not change the negative.) modality label = predicted phenotype.
BZ_SIGNED = ["borzoi_logsed_liver", "borzoi_logsed_allliver", "borzoi_acc_delta"]
AG_SIGNED = ["ag_gene_lfc", "ag_gene_lfc_alltracks", "ag_accessibility_delta",
             "ag_dnase_delta", "ag_splice_score"]


def build_eqtl():
    lab = pd.read_csv(LAB_EQTL, sep="\t")
    lab["cp"] = [cp(c, p) for c, p in zip(lab.chr, lab.pos_hg38)]
    lab["chr"] = lab["chr"].map(nc)
    bz = pd.read_csv(BORZOI_EQTL, sep="\t")
    ag = pd.read_csv(AG_EQTL, sep="\t")
    bz["cp"] = [cp(c, p) for c, p in zip(bz.chr, bz.pos_hg38)]
    ag["cp"] = [cp(c, p) for c, p in zip(ag.chr, ag.pos_hg38)]

    # one feature row per position (dedup: prefer the gene matching the label feature_id,
    # else the row with the strongest |logsed| / |lfc| — deterministic)
    bz["_absl"] = pd.to_numeric(bz["borzoi_logsed_liver"], errors="coerce").abs()
    ag["_absl"] = pd.to_numeric(ag["ag_gene_lfc"], errors="coerce").abs()

    rows = []
    n_unres = 0
    for _, r in lab.iterrows():
        rec = dict(variant=r["variant"], chr=r["chr"], pos_hg38=int(r["pos_hg38"]),
                   ref=str(r["ref"]).upper(), alt=str(r["alt"]).upper(),
                   sign=int(r["sign"]), maf=r.get("maf", np.nan),
                   feature_id=r.get("feature_id"), leakage_tier=r["leakage_tier"],
                   panel="eqtl_broadaway")
        # --- borzoi (choose gene-matched row, else max |logsed|) ---
        bsub = bz[bz.cp == r["cp"]]
        gm = bsub[bsub["gene"].astype(str) == str(r["feature_id"])]
        brow = (gm.sort_values("_absl", ascending=False).iloc[0] if len(gm)
                else bsub.sort_values("_absl", ascending=False).iloc[0] if len(bsub)
                else None)
        om_b = 0
        if brow is not None:
            om_b = orient_mult(rec["ref"], rec["alt"], brow["hg38_ref"], brow["hg38_alt"])
            if om_b != 0:
                for c in BZ_SIGNED:
                    rec[c] = pd.to_numeric(pd.Series([brow.get(c)]), errors="coerce").iloc[0] * om_b
                rec["variant_tss_dist"] = pd.to_numeric(
                    pd.Series([brow.get("variant_tss_dist")]), errors="coerce").iloc[0]
                rec["fold_sign_agreement"] = pd.to_numeric(
                    pd.Series([brow.get("fold_sign_agreement")]), errors="coerce").iloc[0]
                rec["_per_fold"] = brow.get("borzoi_logsed_per_fold")
                rec["_om_b"] = om_b
        # --- alphagenome (gene-matched else max |lfc|) ---
        asub = ag[ag.cp == r["cp"]]
        agm_ = asub[asub["gene"].astype(str) == str(r["feature_id"])]
        arow = (agm_.sort_values("_absl", ascending=False).iloc[0] if len(agm_)
                else asub.sort_values("_absl", ascending=False).iloc[0] if len(asub)
                else None)
        if arow is not None:
            om_a = orient_mult(rec["ref"], rec["alt"], arow["hg38_ref"], arow["hg38_alt"])
            if om_a != 0:
                for c in AG_SIGNED:
                    rec[c] = pd.to_numeric(pd.Series([arow.get(c)]), errors="coerce").iloc[0] * om_a
        if brow is None and arow is None:
            n_unres += 1
        rows.append(rec)
    df = pd.DataFrame(rows)
    feat_cols = BZ_SIGNED + AG_SIGNED
    have = df[feat_cols].notna().any(axis=1)
    log(f"[eqtl] labels={len(lab)}  with>=1 signed feature={int(have.sum())}  "
        f"none={int((~have).sum())}  unresolved-orient dropped implicitly")
    df = df[have].copy()
    return df, feat_cols, "expression", "clean_primary", "CERTIFIED_PRIMARY"


# ============================================================ caQTL matrix (accessibility)
CAQTL_SIGNED = ["cbp_logfc_labelframe", "ag_atac_delta_labelframe",
                "ag_dnase_delta_labelframe", "borzoi_atac_delta_labelframe",
                "borzoi_dnase_delta_labelframe"]


def build_caqtl():
    if not os.path.exists(FEAT_CAQTL):
        log(f"[caqtl] feature table absent ({FEAT_CAQTL}) — SKIP (run src/79 merge first)")
        return None
    df = pd.read_csv(FEAT_CAQTL, sep="\t")
    df["chr"] = df["chr"].map(nc)
    if "is_peak_lead" in df.columns:
        n0 = len(df)
        df = df[df["is_peak_lead"].astype(str).str.upper() == "TRUE"].copy()
        log(f"[caqtl] independent peak-leads {len(df)}/{n0}")
    df["sign"] = pd.to_numeric(df["sign"], errors="coerce")
    feat_cols = [c for c in CAQTL_SIGNED if c in df.columns]
    have = df[feat_cols].notna().any(axis=1) & df["sign"].notna()
    df = df[have].copy()
    df["panel"] = "caqtl_currin"
    df["variant_tss_dist"] = pd.to_numeric(df.get("tss_or_peak_dist"), errors="coerce")
    df["sign"] = df["sign"].astype(int)
    log(f"[caqtl] leads with >=1 accessibility feature & sign = {len(df)}  "
        f"features={feat_cols}")
    return df, feat_cols, "accessibility", "clean_secondary", "CERTIFIED_SECONDARY"


# ============================================================ sQTL matrix (splice; EXPLORATORY)
def build_sqtl():
    if not os.path.exists(FEAT_SQTL):
        log(f"[sqtl] feature table absent ({FEAT_SQTL}) — SKIP")
        return None
    df = pd.read_csv(FEAT_SQTL, sep="\t")
    df["chr"] = df["chr"].map(nc)
    df["sign"] = pd.to_numeric(df["sign"], errors="coerce")
    # only ag_splice_score is potentially signed; spliceai DS are magnitude (unsigned)
    cand = [c for c in ["ag_splice_score"] if c in df.columns]
    for c in cand:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    feat_cols = cand
    if not feat_cols:
        log("[sqtl] no signed splice feature available -> magnitude-only, cannot sign-benchmark")
        return None
    have = df[feat_cols].notna().any(axis=1) & df["sign"].notna()
    df = df[have].copy()
    df["panel"] = "sqtl_gtex_liver"
    df["variant_tss_dist"] = pd.to_numeric(df.get("tss_or_peak_dist"), errors="coerce")
    df["sign"] = df["sign"].astype(int)
    log(f"[sqtl] leads with signed splice feature & sign = {len(df)}  "
        f"[LEAKAGE_EXPLORATORY — GTEx in Borzoi+AG training]")
    return df, feat_cols, "splice", "leakage_exploratory", "EXPLORATORY_LEAKAGE_FLAGGED"


# ============================================================ ML machinery
def enet(C=0.1, l1=0.5):
    return Pipeline([("sc", StandardScaler()),
                     ("clf", LogisticRegression(penalty="elasticnet", solver="saga",
                                                C=C, l1_ratio=l1, max_iter=5000,
                                                class_weight="balanced"))])


def _prep_X(df, feat_cols):
    X = df[feat_cols].apply(pd.to_numeric, errors="coerce").to_numpy(dtype=float)
    X = np.nan_to_num(X, nan=0.0)     # feature-absent = neutral 0 (post-orientation)
    return X


def loco_oof(df, feat_cols, make_est, groups, tune=False):
    """Leave-one-chromosome-out pooled out-of-fold P(sign=+1). If tune: inner-LOCO
    grid over ENET params (pooled-inner-OOF auROC), else make_est() as given."""
    y = (df["sign"].to_numpy() > 0).astype(int)
    X = _prep_X(df, feat_cols)
    g = groups
    oof = np.full(len(df), np.nan)
    chosen = []
    for held in pd.unique(g):
        tr = g != held
        te = g == held
        if tr.sum() < 5 or len(np.unique(y[tr])) < 2:
            oof[te] = np.nan
            continue
        if tune:
            best, best_auc = (ENET_C[0], ENET_L1[1]), -1
            gi = g[tr]
            for C in ENET_C:
                for l1 in ENET_L1:
                    inner = np.full(tr.sum(), np.nan)
                    Xi, yi = X[tr], y[tr]
                    for h2 in pd.unique(gi):
                        it = gi != h2
                        iv = gi == h2
                        if it.sum() < 5 or len(np.unique(yi[it])) < 2:
                            continue
                        m = enet(C, l1).fit(Xi[it], yi[it])
                        inner[iv] = m.predict_proba(Xi[iv])[:, 1]
                    ok = ~np.isnan(inner)
                    if ok.sum() > 10 and len(np.unique(yi[ok])) == 2:
                        a = roc_auc_score(yi[ok], inner[ok])
                        if a > best_auc:
                            best_auc, best = a, (C, l1)
            est = enet(*best)
            chosen.append(best)
        else:
            est = make_est()
        est.fit(X[tr], y[tr])
        oof[te] = est.predict_proba(X[te])[:, 1]
    ok = ~np.isnan(oof)
    auc = roc_auc_score(y[ok], oof[ok]) if len(np.unique(y[ok])) == 2 else np.nan
    return auc, oof, y, ok, chosen


def random_oof(df, feat_cols, make_est, y, seed=7, k=5):
    """Random k-fold pooled OOF (fixed est) — for the leakage-gap vs LOCO."""
    X = _prep_X(df, feat_cols)
    idx = np.arange(len(df))
    rng = np.random.default_rng(seed)
    fold = rng.integers(0, k, len(df))
    oof = np.full(len(df), np.nan)
    for f in range(k):
        tr, te = fold != f, fold == f
        if tr.sum() < 5 or len(np.unique(y[tr])) < 2:
            continue
        m = make_est().fit(X[tr], y[tr])
        oof[te] = m.predict_proba(X[te])[:, 1]
    ok = ~np.isnan(oof)
    return roc_auc_score(y[ok], oof[ok]) if len(np.unique(y[ok])) == 2 else np.nan


def auroc_score(y, s, ok=None):
    if ok is None:
        ok = ~np.isnan(s)
    if len(np.unique(y[ok])) < 2:
        return np.nan
    return roc_auc_score(y[ok], s[ok])


def block_bootstrap(y, score, groups, ok, nboot=2000, seed=123):
    """CI by resampling whole chromosomes with replacement."""
    rng = np.random.default_rng(seed)
    chroms = pd.unique(groups[ok])
    aucs = []
    yo, so, go = y[ok], score[ok], np.asarray(groups)[ok]
    for _ in range(nboot):
        pick = rng.choice(chroms, size=len(chroms), replace=True)
        idx = np.concatenate([np.where(go == c)[0] for c in pick])
        if len(np.unique(yo[idx])) < 2:
            continue
        aucs.append(roc_auc_score(yo[idx], so[idx]))
    if not aucs:
        return (np.nan, np.nan)
    return (float(np.percentile(aucs, 2.5)), float(np.percentile(aucs, 97.5)))


def block_bootstrap_diff(y, s_model, s_base, groups, ok, nboot=2000, seed=321):
    """Paired CI of auROC(model)-auROC(baseline) over resampled chromosomes."""
    rng = np.random.default_rng(seed)
    chroms = pd.unique(groups[ok])
    yo, mo, bo, go = y[ok], s_model[ok], s_base[ok], np.asarray(groups)[ok]
    diffs = []
    for _ in range(nboot):
        pick = rng.choice(chroms, size=len(chroms), replace=True)
        idx = np.concatenate([np.where(go == c)[0] for c in pick])
        if len(np.unique(yo[idx])) < 2:
            continue
        diffs.append(roc_auc_score(yo[idx], mo[idx]) - roc_auc_score(yo[idx], bo[idx]))
    if not diffs:
        return (np.nan, np.nan, np.nan)
    return (float(np.mean(diffs)), float(np.percentile(diffs, 2.5)),
            float(np.percentile(diffs, 97.5)))


def permutation_p(df, feat_cols, groups, obs_auc, nperm=1000, seed=99):
    """Label-permutation null with a FIXED-hyperparam elastic-net (matched observed
    is computed the same fixed way so the p is internally consistent)."""
    rng = np.random.default_rng(seed)
    y = (df["sign"].to_numpy() > 0).astype(int)
    # matched observed under the fixed-hyperparam estimator
    obs_fixed, _, _, _, _ = loco_oof(df, feat_cols, lambda: enet(0.1, 0.5), groups, tune=False)
    null = []
    dfp = df.copy()
    for _ in range(nperm):
        perm = rng.permutation(y)
        dfp["sign"] = np.where(perm > 0, 1, -1)
        a, _, _, _, _ = loco_oof(dfp, feat_cols, lambda: enet(0.1, 0.5), groups, tune=False)
        if not np.isnan(a):
            null.append(a)
    null = np.array(null)
    p = (1 + int(np.sum(null >= obs_fixed))) / (1 + len(null))
    return float(p), float(obs_fixed), (float(np.mean(null)) if len(null) else np.nan), len(null)


# ============================================================ baselines
def baseline_scores(df, panel_kind, feat_cols):
    """Return dict name -> (score array, is_pooled_logistic:bool). Higher score => sign +1."""
    n = len(df)
    out = {}
    # aggregated signed-feature mean (already label-frame oriented)
    sm = df[feat_cols].apply(pd.to_numeric, errors="coerce")
    out["agg_signed_mean"] = (sm.mean(axis=1, skipna=True).to_numpy(), False)
    if panel_kind == "expression":
        primary = pd.to_numeric(df.get("borzoi_logsed_liver"), errors="coerce").to_numpy()
        out["aggregated_signed_logSED"] = (primary.copy(), False)
        # |logSED|-gated sign: signed where |.|>median else 0 (abstain)
        thr = np.nanmedian(np.abs(primary))
        gated = np.where(np.abs(primary) > thr, np.sign(primary), 0.0)
        out["logSED_gated_sign"] = (gated, False)
        # fold-unanimous zero-shot rule: signed mean-per-fold if all folds agree, else 0
        fu = np.zeros(n)
        pf = df.get("_per_fold")
        omb = df.get("_om_b")
        for i in range(n):
            s = pf.iloc[i] if pf is not None else None
            om = omb.iloc[i] if omb is not None else 1
            if not isinstance(s, str):
                continue
            try:
                vals = np.array([float(x) for x in s.split(",")]) * (om if om == om else 1)
            except Exception:
                continue
            if len(vals) and np.all(np.sign(vals) == np.sign(vals[0])) and vals[0] != 0:
                fu[i] = np.sign(vals[0]) * np.abs(vals).mean()
        out["fold_unanimous_rule"] = (fu, False)
    return out


def positional_control(df, groups, y):
    """MAF + TSS-distance-only logistic, LOCO pooled-OOF. Proves biology != AF/position."""
    cols = []
    if "maf" in df.columns:
        cols.append(pd.to_numeric(df["maf"], errors="coerce"))
    d = pd.to_numeric(df.get("variant_tss_dist"), errors="coerce")
    cols += [d, d.abs()]
    Xp = np.column_stack([c.to_numpy() for c in cols])
    Xp = np.nan_to_num(Xp, nan=0.0)
    g = groups
    oof = np.full(len(df), np.nan)
    for held in pd.unique(g):
        tr, te = g != held, g == held
        if tr.sum() < 5 or len(np.unique(y[tr])) < 2:
            continue
        m = Pipeline([("sc", StandardScaler()),
                      ("clf", LogisticRegression(max_iter=2000, class_weight="balanced"))])
        m.fit(Xp[tr], y[tr])
        oof[te] = m.predict_proba(Xp[te])[:, 1]
    return oof


# ============================================================ SORT1 unit check
def sort1_check(df, feat_cols, oof, y, ok):
    hit = df.reset_index(drop=True)
    m = (hit["chr"].astype(str) == SORT1_CHR) & (hit["pos_hg38"].astype("Int64") == SORT1_POS)
    if not m.any():
        return "SORT1 rs12740374 not in this panel's analysis set"
    i = np.where(m.to_numpy())[0][0]
    meas = int(hit.iloc[i]["sign"])
    pred = oof[i]
    agg = pd.to_numeric(hit.iloc[i][feat_cols], errors="coerce").mean()
    return (f"SORT1 present: measured_sign={meas:+d} (expect +1); "
            f"model P(+)={pred:.3f}; signed-feature-mean={agg:+.4g} "
            f"-> {'PASS' if (pred==pred and pred>0.5) else 'check'}")


# ============================================================ run one panel
def run_panel(built, nperm, nboot, do_perm=True):
    df, feat_cols, kind, tier, role = built
    df = df.reset_index(drop=True)
    groups = df["chr"].to_numpy()
    n = len(df)
    n_pos = int((df["sign"] > 0).sum())
    rows = []

    # --- primary estimator: nested-LOCO-tuned elastic-net ---
    auc_en, oof_en, y, ok_en, chosen = loco_oof(df, feat_cols, None, groups, tune=True)
    ci_en = block_bootstrap(y, oof_en, groups, ok_en, nboot=nboot)
    rand_en = random_oof(df, feat_cols, lambda: enet(0.1, 0.5), y)
    perm_p = perm_obs = perm_mean = None
    n_null = 0
    if do_perm and not np.isnan(auc_en):
        perm_p, perm_obs, perm_mean, n_null = permutation_p(df, feat_cols, groups, auc_en, nperm=nperm)
    s1 = sort1_check(df, feat_cols, oof_en, y, ok_en)
    log(f"[{df['panel'].iloc[0]}] elastic-net LOCO pooled-OOF auROC={auc_en:.4f} "
        f"CI[{ci_en[0]:.3f},{ci_en[1]:.3f}] perm_p={perm_p} n={n} pos={n_pos} "
        f"random-split={rand_en:.4f} leakage_gap(rand-loco)={ (rand_en-auc_en) if rand_en==rand_en else float('nan'):.4f}")
    log(f"        chosen (C,l1) modes: {pd.Series(chosen).value_counts().to_dict() if chosen else 'n/a'}")
    log(f"        {s1}")

    rows.append(dict(panel=df["panel"].iloc[0], modality=kind, leakage_tier=tier,
                     endpoint_role=role, model="elastic_net_nestedLOCO",
                     n=n, n_pos=n_pos, n_features=len(feat_cols),
                     auroc=auc_en, ci_lo=ci_en[0], ci_hi=ci_en[1],
                     perm_p=perm_p, perm_obs_fixed=perm_obs, perm_null_mean=perm_mean,
                     n_perm=n_null, random_split_auroc=rand_en,
                     leakage_gap=(rand_en - auc_en) if rand_en == rand_en else np.nan,
                     sort1=s1))

    # --- GBT sensitivity (fixed) ---
    def gbt():
        return HistGradientBoostingClassifier(max_depth=3, learning_rate=0.05,
                                               max_iter=200, l2_regularization=1.0,
                                               class_weight="balanced", random_state=0)
    auc_gbt, oof_gbt, _, ok_gbt, _ = loco_oof(df, feat_cols, gbt, groups, tune=False)
    ci_gbt = block_bootstrap(y, oof_gbt, groups, ok_gbt, nboot=nboot)
    rows.append(dict(panel=df["panel"].iloc[0], modality=kind, leakage_tier=tier,
                     endpoint_role="SENSITIVITY", model="gbt_fixed",
                     n=n, n_pos=n_pos, n_features=len(feat_cols),
                     auroc=auc_gbt, ci_lo=ci_gbt[0], ci_hi=ci_gbt[1],
                     perm_p=np.nan, random_split_auroc=np.nan, leakage_gap=np.nan, sort1=""))

    # --- baselines ---
    base = baseline_scores(df, kind, feat_cols)
    # positional control (pooled-OOF logistic)
    pos_oof = positional_control(df, groups, y)
    base["MAF_TSSdist_positional_logistic"] = (pos_oof, True)

    diffs = {}
    for name, (score, is_log) in base.items():
        score = np.asarray(score, dtype=float)
        okb = ~np.isnan(score)
        a = auroc_score(y, score, okb)
        cib = block_bootstrap(y, score, groups, okb, nboot=nboot)
        # paired diff model - baseline on shared rows
        shared = ok_en & okb
        dmean = dlo = dhi = np.nan
        if shared.sum() > 10 and len(np.unique(y[shared])) == 2:
            dmean, dlo, dhi = block_bootstrap_diff(y, oof_en, score, groups, shared, nboot=nboot)
        diffs[name] = (dmean, dlo, dhi)
        rows.append(dict(panel=df["panel"].iloc[0], modality=kind, leakage_tier=tier,
                         endpoint_role="BASELINE", model=name,
                         n=int(okb.sum()), n_pos=n_pos, n_features=len(feat_cols),
                         auroc=a, ci_lo=cib[0], ci_hi=cib[1],
                         perm_p=np.nan, random_split_auroc=np.nan,
                         leakage_gap=np.nan,
                         diff_model_minus_this_mean=dmean,
                         diff_model_minus_this_ci_lo=dlo,
                         diff_model_minus_this_ci_hi=dhi, sort1=""))
        log(f"        baseline {name}: auROC={a:.4f} CI[{cib[0]:.3f},{cib[1]:.3f}]  "
            f"model-minus-this: {dmean if dmean==dmean else float('nan'):.4f} "
            f"CI[{dlo if dlo==dlo else float('nan'):.3f},{dhi if dhi==dhi else float('nan'):.3f}]")

    summary = dict(panel=df["panel"].iloc[0], modality=kind, leakage_tier=tier,
                   endpoint_role=role, n=n, n_pos=n_pos, n_features=len(feat_cols),
                   enet_auroc=auc_en, enet_ci_lo=ci_en[0], enet_ci_hi=ci_en[1],
                   enet_perm_p=perm_p, gbt_auroc=auc_gbt,
                   random_split_auroc=rand_en,
                   leakage_gap=(rand_en - auc_en) if rand_en == rand_en else None,
                   sort1=s1,
                   baseline_auroc={k: float(auroc_score(y, np.asarray(v[0], float)))
                                   if not np.isnan(auroc_score(y, np.asarray(v[0], float),
                                                               ~np.isnan(np.asarray(v[0], float)))) else None
                                   for k, v in base.items()},
                   beats_baseline_ci_separated={k: (diffs[k][1] is not None
                                                    and diffs[k][1] == diffs[k][1]
                                                    and diffs[k][1] > 0)
                                                for k in diffs})
    return rows, summary


# ============================================================ main
def main():
    raise SystemExit(
        "RETIRED: src/80 fits supervised models on AlphaGenome outputs and is "
        "disabled to enforce the AlphaGenome output-use restriction. Use the "
        "zero-shot replacements src/84_caqtl_zeroshot.py and "
        "src/85_eqtl_signal_diagnose.py. Existing outputs are provenance-only."
    )
    ap = argparse.ArgumentParser()
    ap.add_argument("--panels", default="eqtl,caqtl,sqtl")
    ap.add_argument("--nperm", type=int, default=1000)
    ap.add_argument("--nboot", type=int, default=2000)
    ap.add_argument("--no-perm", action="store_true")
    args = ap.parse_args()
    os.makedirs(SF, exist_ok=True)

    builders = {"eqtl": build_eqtl, "caqtl": build_caqtl, "sqtl": build_sqtl}
    all_rows, summaries = [], {}
    for p in args.panels.split(","):
        p = p.strip()
        if p not in builders:
            continue
        log(f"\n===== PANEL {p} =====")
        built = builders[p]()
        if built is None:
            summaries[p] = {"panel": p, "status": "SKIPPED_no_features"}
            continue
        rows, summ = run_panel(built, args.nperm, args.nboot, do_perm=not args.no_perm)
        all_rows += rows
        summaries[p] = summ

    res = pd.DataFrame(all_rows)
    res.to_csv(OUT_RESULTS, sep="\t", index=False)
    log(f"WROTE {OUT_RESULTS} ({len(res)} rows)")

    # ---- verdict / GO-NO-GO ----
    eq = summaries.get("eqtl", {})
    primary_go = False
    reasons = []
    if eq.get("enet_ci_lo") is not None:
        bar_ok = eq["enet_ci_lo"] > PRIMARY_BAR
        beats = eq.get("beats_baseline_ci_separated", {})
        need = ["fold_unanimous_rule", "logSED_gated_sign", "aggregated_signed_logSED",
                "MAF_TSSdist_positional_logistic"]
        beats_all = all(beats.get(k, False) for k in need if k in beats)
        primary_go = bool(bar_ok and beats_all)
        reasons.append(f"lower95CI={eq['enet_ci_lo']:.4f} {'>' if bar_ok else '<='} bar {PRIMARY_BAR}")
        reasons.append(f"beats-all-baselines(CI-separated)={beats_all}: "
                       + ", ".join(f"{k}={beats.get(k)}" for k in need if k in beats))
    else:
        reasons.append("eqtl panel not runnable")

    # Bonferroni across all non-primary elastic-net panel tests
    nonprimary = [k for k in summaries if k != "eqtl" and "enet_perm_p" in summaries.get(k, {})]
    m_tests = max(1, len(nonprimary))
    for k in nonprimary:
        pp = summaries[k].get("enet_perm_p")
        summaries[k]["bonferroni_alpha"] = 0.05 / m_tests
        summaries[k]["perm_p_bonferroni_sig"] = (pp is not None and pp < 0.05 / m_tests)

    # caQTL vs eQTL head-to-head (the review's foregrounded question)
    caq = summaries.get("caqtl", {})
    caq_vs_eqtl = None
    if isinstance(caq, dict) and caq.get("enet_auroc") is not None and eq.get("enet_auroc") is not None:
        caq_vs_eqtl = {
            "eqtl_expression_auroc": eq.get("enet_auroc"),
            "caqtl_accessibility_auroc": caq.get("enet_auroc"),
            "accessibility_beats_expression": bool(caq.get("enet_auroc") > eq.get("enet_auroc")),
            "note": "point estimates; different variant sets & n — not a paired test"}

    verdict = {
        "preregistered_primary": {
            "estimator": "elastic_net_nestedLOCO",
            "panel": "eqtl_broadaway_clean_primary",
            "statistic": "pooled_out_of_fold_sign_auROC_leave_one_chromosome_out",
            "go_criterion": f"block_bootstrap_lower95_CI > {PRIMARY_BAR} AND CI-separated beat of "
                            "fold_unanimous, logSED_gated_sign, aggregated_signed_logSED, "
                            "MAF+TSSdist positional logistic",
            "result": eq,
            "PRIMARY_GO": primary_go,
            "reasons": reasons,
        },
        "caqtl_vs_eqtl_head_to_head": caq_vs_eqtl,
        "panels": summaries,
        "multiplicity": {"primary": "single locked endpoint",
                         "nonprimary_bonferroni_m": m_tests,
                         "nonprimary_panels": nonprimary},
        "firewall": "APPLY-ONLY: benchmark result only; NO per-locus direction emitted on "
                    "eQTL-absent/convergence set. caQTL/sQTL never a scored convergence channel.",
        "leakage_policy": "eQTL/caQTL = clean (independent assays, not in model training). "
                          "sQTL = GTEx = leakage_exploratory, NEVER certified.",
        "generated": time.strftime("%Y-%m-%d %H:%M:%S"),
    }
    with open(OUT_VERDICT, "w") as f:
        json.dump(verdict, f, indent=2, default=lambda o: None if isinstance(o, float) and np.isnan(o) else o)
    log(f"WROTE {OUT_VERDICT}")
    log(f"\n{'='*70}\nPRIMARY_GO = {primary_go}\n  " + "\n  ".join(reasons) + f"\n{'='*70}")
    _write_readme(verdict)


def _write_readme(v):
    p = v["preregistered_primary"]
    eq = p["result"]
    lines = [
        "# Phase-5 HARDENED direction benchmark (src/80_direction_hardened.py)",
        "",
        "## Pre-registered primary endpoint (LOCKED before any run)",
        "- Estimator: **elastic-net logistic**, nested leave-one-chromosome-out (inner LOCO tune, outer LOCO report).",
        "- Panel: **eQTL Broadaway liver** (clean_primary; independent microarray, NOT in Borzoi/AlphaGenome training).",
        "- Statistic: **pooled out-of-fold sign-auROC** (one auROC per panel; per-fold auROC is undefined on 1-4-example chromosomes).",
        f"- GO criterion: block-bootstrap **lower-95% CI(auROC) > {PRIMARY_BAR}** AND CI-separated beat "
        "(lower-95% of paired block-bootstrap difference > 0) of the fold-unanimous rule, "
        "|logSED|-gated sign, aggregated signed logSED, AND a MAF+TSS-distance-only positional logistic.",
        "- Significance: >=1000x label-permutation null (fixed-hyperparam estimator, matched observed). "
        "CI: block bootstrap resampling whole chromosomes. Bonferroni for all non-primary panels.",
        "",
        "## Hardening (every item a 5-lens review fix)",
        "1. Leakage-tiered labels: eQTL clean_primary CERTIFIED; caQTL clean_secondary CERTIFIED; "
        "GTEx sQTL leakage_exploratory NEVER certified.",
        "2. Feature-modality matching: eQTL->expression (Borzoi logSED, AG RNA head); "
        "caQTL->ACCESSIBILITY only (ChromBPNet/AG-ATAC-DNASE/Borzoi-ATAC); sQTL->splice.",
        "3. Independent LEADS only (is_signal_lead / peak-lead), not LD-pseudoreplicated members.",
        "4. Orientation: every signed feature re-expressed in the label REF->ALT frame via an explicit "
        "orient_mult (allele/strand-swap propagation); strand-ambiguous A/T & C/G hard-dropped upstream; "
        "SORT1 rs12740374 sign unit-check.",
        "5. Positional/MAF features EXCLUDED from the sequence model; used only in the positional-control baseline the model must beat.",
        "6. APPLY-ONLY firewall: benchmark result only — NEVER out-of-sample per-locus direction on the "
        "convergence/eQTL-absent set; caQTL/sQTL never a scored convergence channel, never summed.",
        "",
        "## Primary result",
        f"- n={eq.get('n')} (pos={eq.get('n_pos')}), features={eq.get('n_features')}",
        f"- elastic-net pooled-OOF auROC = **{eq.get('enet_auroc')}** "
        f"CI[{eq.get('enet_ci_lo')}, {eq.get('enet_ci_hi')}], perm_p={eq.get('enet_perm_p')}",
        f"- random-split auROC = {eq.get('random_split_auroc')} (leakage-gap = {eq.get('leakage_gap')})",
        f"- SORT1 unit-check: {eq.get('sort1')}",
        f"- **PRIMARY_GO = {p['PRIMARY_GO']}**  ({'; '.join(p['reasons'])})",
        "",
        "## Outputs",
        "- `direction_hardened_results.csv` — per (panel x model/baseline): auROC, block-bootstrap CI, "
        "perm-p, random-split auROC, leakage-gap, model-minus-baseline paired CI.",
        "- `direction_hardened_verdict.json` — pre-registration, GO/NO-GO, caQTL-vs-eQTL head-to-head, Bonferroni.",
        "",
        "Interpretation guide: a NEGATIVE primary (no CI-separated rescue) is a pre-registered, "
        "thesis-reinforcing result — sequence models fail QTL DIRECTION even under supervision, so seqfunc "
        "stays magnitude/mechanism-only and never enters convergence direction scoring.",
    ]
    with open(OUT_README, "w") as f:
        f.write("\n".join(lines) + "\n")
    log(f"WROTE {OUT_README}")


if __name__ == "__main__":
    main()
