#!/usr/bin/env python3
"""
84_caqtl_zeroshot.py  —  ToS-CLEAN caQTL direction benchmark (Phase 6, WS-1).

WHY THIS SUPERSEDES THE caQTL ARM OF 80_direction_hardened.py
-------------------------------------------------------------
The red-team critique (SEQFUNC_CAMPAIGN_CRITIQUE.md, F2/F4) raised two valid,
source-verified problems with the old caQTL "0.707 WIN":

  1. LICENSING (F2): the old elastic-net/GBT were TRAINED on AlphaGenome output
     features (ag_atac_delta_labelframe, ag_dnase_delta_labelframe). The
     AlphaGenome FAQ states verbatim: "Outputs generated by AlphaGenome should
     not be used for the training of other machine learning models" + "non-
     commercial use only". => any model TRAINED on ag_* is non-compliant.

  2. BASELINE / PSEUDO-REPLICATION (F4): the old report never showed that the
     5-feature ensemble beats the strongest INDIVIDUAL model, and it scored
     11,896 nominal peak-leads that are NOT LD-independent signals (Currin's
     inferential unit is FDR<5% caPeaks / 2,126 LD-clumped signals).

FIX (this script):
  * NO TRAINED MODEL on any AlphaGenome feature. We report per-model ZERO-SHOT
    sign-auROC (each signed sequence delta scored directly against the measured
    caQTL sign). AlphaGenome ATAC/DNase are reported ONLY as zero-shot
    annotation/evaluation (allowed under the FAQ), flagged, never trained on.
  * An OPEN-only zero-shot aggregate (mean of the 3 open-license signed deltas:
    Borzoi ATAC, Borzoi DNase, ChromBPNet HepG2) is reported for reference — it
    is a fixed average, not a fitted estimator, so it is ToS-clean AND cannot
    overfit. The headline is the strongest SINGLE open model, not an ensemble.
  * Signal-level clustering: peak-leads are distance-clumped per chromosome to a
    single representative (min caQTL p) so the reported n is signal-level, not
    the pseudo-replicated 11,896. Variant-level numbers are kept as a sensitivity.
  * Block-bootstrap CI (resample whole chromosomes = LD-robust), >=1000x label-
    permutation null, MAF+peak-distance positional baseline.

SOURCE (correct description): Currin et al. 2025, Genome Research (PMC12212085) —
  caQTLs from BULK LIVER tissue, n=138 deceased donors (NOT primary hepatocytes).
  Official unit = FDR<5% caPeaks (35,361); 2,126 LD-clumped multi-peak signals.

FRAMING (do NOT overclaim): this is "zero-shot sequence scores show moderate sign
  discrimination on an independent bulk-liver caQTL panel." It is NOT a MASLD
  result, NOT a proximal-chromatin-vs-emergent-expression mechanism claim, and
  NOT paired with the eQTL panel (different assay/ascertainment/n).

APPLY-ONLY FIREWALL (unchanged): caQTL is the SAME genetic axis as eQTL — used
  for labels/corroboration only, NEVER summed into convergence, NEVER emitted as a
  per-locus direction call on eQTL-absent/convergence loci.
"""
import json
import os
import time

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

ROOT = os.environ.get(
    "MASLD_PROJECT_ROOT",
    "/gpfs/commons/groups/sanjana_lab/Cas13/MASLD_library_design")
SF = os.path.join(ROOT, "GWAS/finemapping/results/seqfunc")
FEAT = os.path.join(SF, "direction_features_caqtl.tsv")
OUT_JSON = os.path.join(SF, "caqtl_zeroshot_verdict.json")
OUT_TSV = os.path.join(SF, "caqtl_zeroshot_permodel.tsv")

CLUMP_BP = 500_000       # signal-level distance clump per chromosome
NBOOT = 2000
NPERM = 1000
SEED = 42

# per-model zero-shot signed deltas (already label-frame oriented in 79_score_panels.py)
OPEN_MODELS = {                       # open license -> eligible for headline
    "borzoi_atac":  "borzoi_atac_delta_labelframe",
    "borzoi_dnase": "borzoi_dnase_delta_labelframe",
    "chrombpnet_hepg2": "cbp_logfc_labelframe",
}
AG_MODELS = {                         # AlphaGenome: zero-shot ANNOTATION ONLY, reported w/ notice
    "alphagenome_atac":  "ag_atac_delta_labelframe",
    "alphagenome_dnase": "ag_dnase_delta_labelframe",
}
AG_NOTICE = ("AlphaGenome outputs are used here strictly as ZERO-SHOT evaluation "
             "(not to train any model), per the AlphaGenome FAQ output restriction; "
             "non-commercial use.")


def log(m):
    print(f"[{time.strftime('%H:%M:%S')}] {m}", flush=True)


def nc(c):
    c = str(c)
    return c[3:] if c.lower().startswith("chr") else c


def auroc(y, s, ok=None):
    if ok is None:
        ok = ~np.isnan(s)
    if ok.sum() == 0 or len(np.unique(y[ok])) < 2:
        return np.nan
    return float(roc_auc_score(y[ok], s[ok]))


def block_bootstrap(y, score, groups, ok, nboot=NBOOT, seed=123):
    """CI by resampling whole chromosomes (LD-robust at the chromosome block)."""
    rng = np.random.default_rng(seed)
    yo, so, go = y[ok], score[ok], np.asarray(groups)[ok]
    chroms = pd.unique(go)
    aucs = []
    for _ in range(nboot):
        pick = rng.choice(chroms, size=len(chroms), replace=True)
        idx = np.concatenate([np.where(go == c)[0] for c in pick])
        if len(np.unique(yo[idx])) < 2:
            continue
        aucs.append(roc_auc_score(yo[idx], so[idx]))
    if not aucs:
        return (np.nan, np.nan)
    return (float(np.percentile(aucs, 2.5)), float(np.percentile(aucs, 97.5)))


def block_bootstrap_diff(y, s_a, s_b, groups, ok, nboot=NBOOT, seed=321):
    """Paired auROC(a)-auROC(b) over resampled chromosomes (both on shared complete-case)."""
    rng = np.random.default_rng(seed)
    yo, ao, bo, go = y[ok], s_a[ok], s_b[ok], np.asarray(groups)[ok]
    chroms = pd.unique(go)
    d = []
    for _ in range(nboot):
        pick = rng.choice(chroms, size=len(chroms), replace=True)
        idx = np.concatenate([np.where(go == c)[0] for c in pick])
        if len(np.unique(yo[idx])) < 2:
            continue
        d.append(roc_auc_score(yo[idx], ao[idx]) - roc_auc_score(yo[idx], bo[idx]))
    if not d:
        return (np.nan, np.nan, np.nan)
    return (float(np.mean(d)), float(np.percentile(d, 2.5)), float(np.percentile(d, 97.5)))


def perm_null_p(y, score, ok, obs, nperm=NPERM, seed=99):
    """Label-permutation null for a FIXED zero-shot score (exact null for this estimator)."""
    rng = np.random.default_rng(seed)
    yo, so = y[ok], score[ok]
    null = []
    for _ in range(nperm):
        yp = rng.permutation(yo)
        if len(np.unique(yp)) < 2:
            continue
        null.append(roc_auc_score(yp, so))
    null = np.asarray(null)
    # two-sided-ish: how often does a random labeling reach the observed |direction|?
    a = max(obs, 1 - obs)
    hit = np.sum((null >= a) | (null <= 1 - a))
    p = (1 + int(hit)) / (1 + len(null))
    return float(p), float(np.mean(null)) if len(null) else np.nan, len(null)


def positional_baseline(df, y, groups):
    """MAF + peak-distance-only logistic, LOCO pooled-OOF. Proves signal != AF/position."""
    cols = [pd.to_numeric(df.get("maf"), errors="coerce"),
            pd.to_numeric(df.get("tss_or_peak_dist"), errors="coerce"),
            pd.to_numeric(df.get("tss_or_peak_dist"), errors="coerce").abs()]
    X = np.nan_to_num(np.column_stack([c.to_numpy() for c in cols]), nan=0.0)
    oof = np.full(len(df), np.nan)
    for held in pd.unique(groups):
        tr, te = groups != held, groups == held
        if tr.sum() < 5 or len(np.unique(y[tr])) < 2:
            continue
        m = Pipeline([("sc", StandardScaler()),
                      ("clf", LogisticRegression(max_iter=2000, class_weight="balanced"))])
        m.fit(X[tr], y[tr])
        oof[te] = m.predict_proba(X[te])[:, 1]
    return oof


def signal_clump(df):
    """One representative (min caQTL p) per CLUMP_BP window per chromosome.
    Deterministic single-linkage-style distance clump on the peak-lead positions."""
    keep = []
    for ch, sub in df.groupby("chr"):
        sub = sub.sort_values("pos_hg38").reset_index()
        last = -10 * CLUMP_BP
        cur = []
        clumps = []
        for _, r in sub.iterrows():
            if r["pos_hg38"] - last > CLUMP_BP and cur:
                clumps.append(cur)
                cur = []
            cur.append(r)
            last = r["pos_hg38"]
        if cur:
            clumps.append(cur)
        for cl in clumps:
            cldf = pd.DataFrame(cl)
            rep = cldf.loc[pd.to_numeric(cldf["pvalue"], errors="coerce").idxmin()]
            keep.append(int(rep["index"]))
    return df.loc[keep].copy()


def score_one(y, score, groups, ok, label):
    a = auroc(y, score, ok)
    lo, hi = block_bootstrap(y, score, groups, ok)
    p, null_mean, n_null = perm_null_p(y, score, ok, a)
    return dict(model=label, auroc=a, ci_lo=lo, ci_hi=hi,
                perm_p=p, perm_null_mean=null_mean, n_perm=n_null, n=int(ok.sum()))


def run_level(df, level):
    y = (pd.to_numeric(df["sign"], errors="coerce").to_numpy() > 0).astype(int)
    groups = df["chr"].astype(str).to_numpy()
    n_pos = int(y.sum())
    log(f"[{level}] n={len(df)} n_pos={n_pos} n_chrom={df['chr'].nunique()}")

    # per-model complete-case
    rows = []
    model_scores = {}
    for label, col in {**OPEN_MODELS, **AG_MODELS}.items():
        s = pd.to_numeric(df.get(col), errors="coerce").to_numpy()
        ok = ~np.isnan(s)
        model_scores[label] = s
        r = score_one(y, s, groups, ok, label)
        r["license"] = "open" if label in OPEN_MODELS else "alphagenome_zeroshot_annotation"
        rows.append(r)

    # open-only zero-shot aggregate (fixed mean, NOT a fitted model)
    open_mat = np.column_stack([model_scores[k] for k in OPEN_MODELS])
    open_agg = np.nanmean(open_mat, axis=1)
    ok_agg = ~np.isnan(open_agg)
    r = score_one(y, open_agg, groups, ok_agg, "open_zeroshot_aggregate_mean")
    r["license"] = "open"
    rows.append(r)

    # positional baseline
    pos = positional_baseline(df, y, groups)
    ok_pos = ~np.isnan(pos)
    r = score_one(y, pos, groups, ok_pos, "positional_MAF_peakdist_logistic")
    r["license"] = "baseline"
    rows.append(r)

    # best single OPEN model, and does it beat positional (CI-separated paired)?
    open_rows = [x for x in rows if x["license"] == "open" and x["model"] in OPEN_MODELS]
    best = max(open_rows, key=lambda x: (x["auroc"] if x["auroc"] == x["auroc"] else -1))
    shared = (~np.isnan(model_scores[best["model"]])) & ok_pos
    dmean, dlo, dhi = block_bootstrap_diff(y, model_scores[best["model"]], pos, groups, shared)
    beat_pos = bool(dlo > 0)

    # does the aggregate beat the best single open model? (justifies/ refutes an ensemble)
    agg_row = [x for x in rows if x["model"] == "open_zeroshot_aggregate_mean"][0]
    shared2 = (~np.isnan(open_agg)) & (~np.isnan(model_scores[best["model"]]))
    ad_mean, ad_lo, ad_hi = block_bootstrap_diff(y, open_agg, model_scores[best["model"]],
                                                 groups, shared2)
    agg_beats_best = bool(ad_lo > 0)

    return dict(level=level, n=len(df), n_pos=n_pos, n_chrom=int(df["chr"].nunique()),
                per_model=rows,
                best_open_model=best["model"], best_open_auroc=best["auroc"],
                best_open_ci=[best["ci_lo"], best["ci_hi"]],
                best_beats_positional=beat_pos,
                best_vs_positional_diff=[dmean, dlo, dhi],
                aggregate_beats_best_single=agg_beats_best,
                aggregate_vs_best_diff=[ad_mean, ad_lo, ad_hi])


def main():
    log(f"reading {FEAT}")
    df = pd.read_csv(FEAT, sep="\t")
    df["chr"] = df["chr"].map(nc)
    df["pos_hg38"] = pd.to_numeric(df["pos_hg38"], errors="coerce")
    df = df.dropna(subset=["pos_hg38", "sign"]).reset_index(drop=True)
    df["pos_hg38"] = df["pos_hg38"].astype(int)

    # variant level (all peak-leads = pseudo-replicated; kept as sensitivity)
    var_level = run_level(df, "variant_level_all_peakleads")

    # signal level (distance-clumped, one representative per CLUMP_BP per chromosome)
    sig = signal_clump(df)
    sig_level = run_level(sig, "signal_level_clumped")

    verdict = dict(
        script="84_caqtl_zeroshot.py",
        source=("Currin et al. 2025 Genome Research (PMC12212085): caQTLs from BULK "
                "LIVER tissue, n=138 donors; official unit FDR<5% caPeaks / 2,126 "
                "LD-clumped signals. NOT primary hepatocytes."),
        tos_compliance=("No model is TRAINED on any AlphaGenome feature. Per-model "
                        "ZERO-SHOT sign-auROC only. " + AG_NOTICE),
        framing=("Zero-shot sequence scores' sign discrimination on an independent "
                 "bulk-liver caQTL panel. NOT a MASLD result; NOT paired with the eQTL "
                 "panel; NOT a proximal-vs-emergent mechanism claim."),
        firewall="APPLY-ONLY: caQTL never summed into convergence; never a per-locus direction call.",
        clump_bp=CLUMP_BP, nboot=NBOOT, nperm=NPERM, seed=SEED,
        variant_level=var_level, signal_level=sig_level,
    )
    with open(OUT_JSON, "w") as fh:
        json.dump(verdict, fh, indent=2)
    log(f"wrote {OUT_JSON}")

    # flat per-model table (both levels)
    flat = []
    for lv in (var_level, sig_level):
        for r in lv["per_model"]:
            flat.append({"level": lv["level"], **r})
    pd.DataFrame(flat).to_csv(OUT_TSV, sep="\t", index=False)
    log(f"wrote {OUT_TSV}")

    # console summary
    for lv in (var_level, sig_level):
        log(f"===== {lv['level']} (n={lv['n']}, n_pos={lv['n_pos']}) =====")
        for r in lv["per_model"]:
            log(f"  {r['model']:34s} auROC={r['auroc']:.4f} "
                f"CI[{r['ci_lo']:.4f},{r['ci_hi']:.4f}] perm_p={r['perm_p']:.4f} "
                f"n={r['n']} [{r['license']}]")
        log(f"  BEST open model = {lv['best_open_model']} ({lv['best_open_auroc']:.4f}); "
            f"beats positional={lv['best_beats_positional']} "
            f"(diff {lv['best_vs_positional_diff'][0]:+.4f} "
            f"CI[{lv['best_vs_positional_diff'][1]:+.4f},{lv['best_vs_positional_diff'][2]:+.4f}]); "
            f"aggregate beats best single={lv['aggregate_beats_best_single']}")


if __name__ == "__main__":
    main()
