#!/bin/bash
#SBATCH --job-name=audit33
#SBATCH --output=/gpfs/commons/groups/sanjana_lab/Cas13/MASLD_library_design/scripts/figures/_c2_rerender/logs/regen_conserved_%j.out
#SBATCH --error=/gpfs/commons/groups/sanjana_lab/Cas13/MASLD_library_design/scripts/figures/_c2_rerender/logs/regen_conserved_%j.err
#SBATCH --partition=cpu
#SBATCH --qos=interactive
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=4:00:00

# Re-run ONLY the conserved-enrichment producer (Script 33, now C2-column-aware)
# + the dependent figS_conserved_core figure. UMAP coords were already
# regenerated by the prior job (17093625).

eval "$(/gpfs/commons/home/jameslee/.local/bin/micromamba shell hook --shell bash)"
micromamba activate rnaseq
set -uo pipefail

BASE=/gpfs/commons/groups/sanjana_lab/Cas13/MASLD_library_design
export MASLD_PROJECT_ROOT="$BASE"
FIG="$BASE/scripts/figures"
ENR_CSV="$BASE/RNA-seq/results/audit_sensitivity/conserved_enrichment.csv"
cd "$BASE"

echo "[$(date '+%F %T')] >>> 33_audit_sensitivity_analyses.R"
Rscript "$BASE/RNA-seq/33_audit_sensitivity_analyses.R"
rc2=$?
echo "[$(date '+%T')] <<< 33_audit_sensitivity_analyses.R rc=$rc2"
if [ -f "$ENR_CSV" ]; then
  echo "ENR CSV mtime: $(stat -c '%y' "$ENR_CSV")"
  echo "--- conserved_enrichment.csv ---"; cat "$ENR_CSV"; echo "--------------------------------"
else
  echo "ERROR: conserved_enrichment.csv STILL not written"
fi

echo ""
echo "[$(date '+%T')] render >>> figS_conserved_core"
log="$FIG/_c2_rerender/logs/figS_conserved_core_staleregen2.log"
timeout 1200 Rscript "$FIG/figS_conserved_core.R" > "$log" 2>&1
rc=$?
if [ $rc -eq 0 ]; then echo "[$(date '+%T')] render <<< figS_conserved_core PASS";
else
  ferr=$(grep -m1 -iE "error|cannot|could not|no such file|not found|unable|object .* not found" "$log" | head -1 | cut -c1-300)
  echo "[$(date '+%T')] render <<< figS_conserved_core FAIL rc=$rc :: $ferr"
fi
echo "[$(date '+%F %T')] DONE producer_rc=$rc2 fig_rc=$rc"
